### ISSUE TITLE
nglview cant show the gromacs trajectory (xtc and tpr)

### ISSUE THREAD

**Issue by hima111997** [nglviewer/nglview#1009]
- Version report

```bash
python -c 'import nglview; print(nglview.__version__)'
i have version 3.0.3
python -c 'import ipywidgets; print(ipywidgets.__version__)'
i have version 7.6.5
```
i have tried to perform the same commands of the transformation found in the docs (https://www.mdanalysis.org/2020/03/09/on-the-fly-transformations/) on my tpr and xtc files using jupyter notebook, but nothing appears (this also happened with the files of the inserted peptide on the previous link). i tried it with psf and dcd files and it worked well.

what is the problem?

this is my code:
```import MDAnalysis as mda
import nglview as nv
import numpy as np
from MDAnalysis import transformations
import warnings
warnings.filterwarnings('ignore') # nglview is missing some PDB-only attributes and complains 
import MDAnalysisData

peptide = MDAnalysisData.datasets.fetch_membrane_peptide()
u = mda.Universe(peptide.topology, peptide.trajectory)
nv.show_mdanalysis(u)
```

**Comment by hainm** [comment]
> import nglview as nv
> import numpy as np
> from MDAnalysis import transformations
> import warnings
> warnings.filterwarnings('ignore') # nglview is missing some PDB-only attributes and complains 
> import MDAnalysisData
> 
> peptide = MDAnalysisData.datasets.fetch_membrane_peptide()
> u = mda.Universe(peptide.topology, peptide.trajectory)
> nv.show_mdanalysis(u)

hi @hima111997 

seems fine in my test:
<img width="1198" alt="image" src="https://user-images.githubusercontent.com/4451957/152695877-d564a510-3683-4507-bb71-f3a3064c2f0b.png">

**Comment by hima111997** [comment]
could the python version affect the output? i have python 3.9

**Comment by hainm** [comment]
Mine is 3.9 too.

**Comment by hima111997** [comment]
okay thank you
