### ISSUE TITLE
ColormakerRegistry doesn't work on google colab

### ISSUE THREAD

**Issue by hamedkhakzad** [nglviewer/nglview#1010]
Hello,

The following example works on jupyter notebook but doesn't work on google colab. There is a problem with defining new color schemes generally on colab. Could you please take a look?

```
ng.color.ColormakerRegistry.add_selection_scheme(
    "my_custom_scheme", [["blue", "1-100"], ["red", "101-1000"]]
)

view = ng.show_pdbid("1EYE", default_representation=False)
view.add_cartoon(color="my_custom_scheme")
view.center()
view
```

**Comment by hainm** [comment]
hi @hamedkhakzad: It's something that colab developers should investigate because I have zero knowledge about that. Cheers.
