### ISSUE TITLE
nglview blank html file as a result of write_html

### ISSUE THREAD

**Issue by JMcsLk** [nglviewer/nglview#1016]
Hello, I've got issue with html export process. In jupyter notebook view of the pdb file works correctly, when I'm trying to export this view by `write_html` as a result there is a blank html file. 

I've already checked few things:

- Version of a packages: _nv: '3.0.3', notebook: '6.4.3', ipywidgets: '7.6.5', ipykernel: '6.4.1'_,
- `jupyter-nbextension enable nglview --py --sys-prefix` -> _result: Validating: OK_

Code:
```
import nglview
view = nglview.show_pdbid('1tsu')
nglview.write_html("demo1.html", [view])

```
_demo1.html_ file has only some icons inside:
![image](https://user-images.githubusercontent.com/44715668/162220001-f26f297c-b37f-4827-b198-2edaf8d0aa70.png)

I'd be grateful for every tip to resolve it.

Marcin.

**Comment by fses91** [comment]
Hi, I am having the same issue. How did you solve it?

**Comment by JMcsLk** [comment]
Before you export html file you have to render it inside jupyter notebook otherwise the html file will be empty.

`import nglview
view = nglview.show_pdbid('1tsu')
view`

then

`nglview.write_html("demo1.html", [view])`

If you want do it outside the jupyter notebook for example in a python script then you have to use some microservice to simulate jupyter rendering in a web browser.

**Comment by fses91** [comment]
Thanks for the fast reply, yes I am trying to do it outside jupyter, do you have already a working solution for that?

**Comment by shouldsee** [comment]
The rendering is probably defined within NGLWidget here https://github.com/nglviewer/nglview/blob/e2f7fe593f24357fb6d5d15fb3cfe2f64c325664/nglview/widget.py#L129

**Comment by hainm** [comment]
@shouldsee  You should run your code in two notebook cells

```
# cell 1
import nglview
import nglview as nv
view = nglview.NGLWidget()
view = nglview.show_pdbid('1tsu')
view

# cell 2
nglview.write_html('embed.html',[view])
```

**Comment by shouldsee** [comment]
> @shouldsee You should run your code in two notebook cells
> 
> ```
> # cell 1
> import nglview
> import nglview as nv
> view = nglview.NGLWidget()
> view = nglview.show_pdbid('1tsu')
> view
> 
> # cell 2
> nglview.write_html('embed.html',[view])
> ```

Yeah that might work. I am mainly looking into create webpages without jupyter, thus avoiding using jupyter runtimes.
