### ISSUE TITLE
how to display vector or arrow by residue of structure 

### ISSUE THREAD

**Issue by neriaaa46** [nglviewer/nglview#1018]
Hi, I try to display arrow between to points in 3D structure 
I found this code: 

stage.loadFile( "rcsb://1crn", { defaultRepresentation: true }).then(function (o) {
  stage.autoView()
});

var shape = new NGL.Shape( "shape" );
shape.addArrow( [ 2, 2, 7 ], [ 30, -3, -3 ], [ 1, 0.5, 1 ], 0.2 );

var shapeComp = stage.addComponentFromObject( shape );
shapeComp.addRepresentation( "buffer" );

But I try to find a way to add arrow or line or vector by residue of the structure and not by two points-( [ 2, 2, 7 ], [ 30, -3, -3 ], [ 1, 0.5, 1 ], 0.2 )
 there is this options ?!

**Comment by hainm** [comment]
Dear @neriaaa46, please post your question in `NGL` repo (this is for `nglview`, the jupyter notebook interface): https://github.com/nglviewer/ngl

Cheers.
