### ISSUE TITLE
nglview with papermill or nbconvert

### ISSUE THREAD

**Issue by izhar1973** [nglviewer/nglview#1019]
Hi,

I am trying to automate an analysis script that uses nglview widget using either papermill or nbconvert --execute.
a prototype for the script would be (test1.ipynb) :

![image](https://user-images.githubusercontent.com/91240130/163883284-638ba3ef-e3f4-49bb-ad32-e3dd593b23b2.png)

for papermill (from jupyter):

import papermill as pm
pm.execute_notebook(input_path='e:/Targets/test1.ipynb',
                    output_path='e:/Targets/test1_out.ipynb')

for nbconvert (from shell): 

jupyter-nbconvert --to notebook --execute test1.ipynb

the script runs correctly when executed on a jupyter-notbook, the demo is rendered and the resulting png file contains its image.
both papermill and nbconvert execute the script, however, the resulting notebooks do not contain a rendered nglview
widget, and the resulting _temp_image.png file is empty.

is there a way to force nglwidget to render its content when executed using either of these tools?
 

- Version report

![image](https://user-images.githubusercontent.com/91240130/163882893-d6af6052-233f-42d5-be8b-3aea23c59dea.png)

Thanks In advance,

Izhar.

**Comment by izhar1973** [comment]
1) Code for the cells :

**Cell1 :**
import nglview as nv
view = nv.demo()
view

**Cell2:**
im = v.render_image(factor=9, trim=True)
view._display_image()
with open(f'E:\Targets\_temp_image.png', 'wb') as fh:
        fh.write(im.value)

2) I've tried also the following threaded version for cell2, which also works fine in jupyter but fails to render under papermill :

import time
def generate_image(v=view):
    im = v.render_image()
    while not im.value:
        time.sleep(0.1)
    with open(f'E:\Targets\_temp_image.png', 'wb') as fh:
        fh.write(im.value)

import threading
thread = threading.Thread(
    target=generate_image,
)
thread.daemon = True
thread.start()

**Comment by fses91** [comment]
For me that doesn't work, the images are all empty.

**Comment by hainm** [comment]
hi @izhar1973: For nbconvert, please see this post: https://github.com/nglviewer/nglview/issues/869#issuecomment-583893346

**Comment by hainm** [comment]
For your example:
```
im = view.render_image(...)
im # not view._display_image()
```

**Comment by hainm** [comment]
Let me know if I missed any of your question.

**Comment by izhar1973** [comment]
Dear Hai,

Thanks for the prompt reply.
I’m afraid that I have oversimplified the use case and thus failed to convey my point clearly.
Please allow me to try once more.
I opt to incorporate nglview into a pipeline that uses MDAnalysis to analyze hundreds of trajectories.
In my hands, the solution given at post #869 works only if the notebook is pre-run manually and the widget state is saved at the end of the run. Otherwise, the resulting HTML is empty, and so is the produced png.  
While one may overcome this limitation by using some browser-based automation, this would inevitably make the whole process cumbersome and hard to replicate and share.
To make the point crystal clear, lets consider the following script, which loads a demo trajectory, runs an rmsf analysis, then plots the rmsf along the trajectory and a nglview snapshot of the system: 

![image](https://user-images.githubusercontent.com/91240130/164727635-bec14439-aea4-4242-99ae-e503df603a1a.png)

Upon a manual run in a browser, the script produces both rmsf plot and ngl image, which can then be incorporated into downstream reports. However, when run using nbconvert (jupyter-nbconvert test.ipynb --to=html --execute), only the plt figure is maintained, while the ngl output is blank :

![image](https://user-images.githubusercontent.com/91240130/164730140-4afdc7b8-f074-4f88-9caa-82e4795818ec.png)



 This different behavior of the nglview widget **poses a limit on its use in headless environments**, as opposed to the plt widget. My question is if there is an existing solution for this use case, or some way to "make it work" in a graceful manner that would allow sharing the developed procedures with others. 

yours,


Izhar.

**Comment by izhar1973** [comment]
**code :**

import MDAnalysis as mda
from MDAnalysis.tests.datafiles import PSF, DCD
from MDAnalysis.analysis import rms
import matplotlib.pyplot as plt
import nglview as nv

u = mda.Universe(PSF, DCD)

protein = u.select_atoms("protein")
c_alphas = protein.select_atoms("name CA")
R = rms.RMSF(c_alphas).run()

plt.plot(c_alphas.resnums, R.results.rmsf)
plt.savefig ('E:/Targets/test_plt.png')

view = nv.show_mdanalysis(u)
view

im = view.render_image()

    with open('E:/Targets/test_nv.png', 'wb') as fh:
        fh.write(im.value)

**Comment by hainm** [comment]
> I opt to incorporate nglview into a pipeline that uses MDAnalysis to analyze hundreds of trajectories.
> In my hands, the solution given at post #869 works only if the notebook is pre-run manually and the widget state is saved at the end of the run. Otherwise, the resulting HTML is empty, and so is the produced png.

> While one may overcome this limitation by using some browser-based automation, this would inevitably make the whole process cumbersome and hard to replicate and share.

Unfortunately, there are only two options above, either running the notebook manually then saving the widget state or using browser-based automation. `nglview` is using `NGL` that requires browser to render the trajectory. 

> This different behavior of the nglview widget poses a limit on its use in headless environments, as opposed to the plt widget. 

Because `plt` widget does not require browser to render the image (I guess). 

By the way, what's the usage for rendering hundreds of notebooks?

**Comment by izhar1973** [comment]
Thanks for the comments.
As for the last question -  when exploring multiple MD trajectories it is often desired to save visual snapshots of the system in particular states for a later manual inspection, as these analyses are often carried on headless nodes. Some solve this issue by producing during the headless session a script that is being used later to generate the images on a machine equipped with a graphical frontend (e.g. https://livecomsjournal.org/index.php/livecoms/article/view/v2i1e21383/975). While this certainly "works", an ideal scenario would merge the two steps and produce images/videos during the headless session (more streamlinged workflow, and easier to share with non-experienced users).

yours,

Izhar.
