### ISSUE TITLE
Can I extract the coordinates from a named atom (if I don't know the index)?

### ISSUE THREAD

**Issue by samuelflores** [nglviewer/nglview#1020]
What if I want to extract positions from certain atoms in a macromolecule? Let's say I know the chain ID, residue numbers, and atom names, and want to use this to retrieve the coordinates of those two atoms? Is that possible? Equivalently, can I extract the atom index given the atom name, residue number, and chain?

**Comment by hainm** [comment]
I am not aware of an easy way to do that in nglview.

**Comment by samuelflores** [comment]
Ah ok. Surely there is some other trick that would enable me to draw a line
between two atoms though.

How is the covalent bond network determined? Is it based only on distance?
How about if I create a selection with just the two atoms, and then use
e.g. Licorice rendering, and greatly increase the minimum covalent bond
length? Then the two atoms would appear to be bonded, and I would get the
line I want. If that would work, kindly tell me how to change the minimum
bond length.

Sam

**Comment by hainm** [comment]
Dear Sam
I have limited knowledge about `NGL` itself. So please ask `NGL` developers here: https://github.com/nglviewer/ngl/issues
