### ISSUE TITLE
Feature request: Initial snapshots

### ISSUE THREAD

**Issue by wangenau** [nglviewer/nglview#1026]
Hello,

while using your project I was thinking of a feature that would greatly improve displaying offline notebooks.
Vispy has the feature that it saves an initial snapshot of the current interactive view as a png to the notebook.
Viewing the unexecuted notebook, e.g., on Github in documentations, it will still show an image.
An example is shown here: https://gitlab.com/nextdft/eminus/-/blob/master/examples/08_visualizer_addon/08_visualizer_addon.ipynb
Vispy at the bottom shows a snapshot, while nglview does not.

And some (maybe) helpful information:
Vispy uses their [jupyter_rfb](https://github.com/vispy/jupyter_rfb) backend for displaying in notebooks.
The snapshot functionality has been added in v0.2.0 in [this](https://github.com/vispy/jupyter_rfb/commit/6c625bb2f1a8c5f7e326ff9783f47fadd32ebecd#diff-d2f34dc196e0daeafe53639e993b3e6ebc179b0e372cbd75ad23dd5092236c12) commit.

Maybe this is something others would like to see as well.

Keep up the good work!

**Comment by hainm** [comment]
Thanks @wangenau for your suggestion.

**Comment by hainm** [comment]
Just curious: how does above differs from NGLView's _display_image?

https://projects.volkamerlab.org/teachopencadd/talktorials/T016_protein_ligand_interactions.html?highlight=nglview
<img width="872" alt="image" src="https://user-images.githubusercontent.com/4451957/176281360-28998d04-68b5-46e9-8552-6fa78bafefaa.png">

**Comment by hainm** [comment]
> If one only creates an interactive 3D view, saves, closes the notebook and opens it again without executing it there is no render of said image.
With said snapshot feature one would see the last render of the 3D view as a placeholder until the cell gets executed again.

I think `nglview` already supports that. Can you please try below:
- Open a new notebook and run
```
import nglview as nv

view = nv.demo()
view
```
- Click "Save Notebook Widget States" --> Here is the key to make the magic work.
<img width="416" alt="image" src="https://user-images.githubusercontent.com/4451957/176482414-41c437b8-92c5-49dd-9d72-3f3ec6e9db78.png">

- Close the notebook and close the jupyter session
- Relaunch the notebook without executing the cell. User can still see the "live" 3D. Let me know if I understand correctly the requested feature.

<img width="1159" alt="image" src="https://user-images.githubusercontent.com/4451957/176482204-a81c2c08-f243-48a3-981f-472e845ad4e6.png">

**Comment by wangenau** [comment]
I didn't know about the option to save widget states, thanks for that!
This works great, but  it still differs a bit from what I desire :smile:
It seems that saving the state only works locally. If I would push the notebook to e.g. Gitlab and look at it in the repo the cell result would still be empty.

The use-case would be for examples and documentations. With this feature one can write the correct code to get an interactive widget and if the notebook is only rendered as plain html one would see the rendered image instead of the widget.

So the minimal test case would be:
1. Create a notebook with an interactive widget
2. Convert it to plain html e.g. with `jupyter nbconvert --to html notebook.ipynb`
3. Still have a render of the widget in the resulting html

**Comment by hainm** [comment]
Try
```
# 1st cell
view.render_image()

# 2nd cell
view._display_image()
```
This will display a static image and I think the data is saved in the notebook. You can check this out: https://projects.volkamerlab.org/teachopencadd/talktorials/T017_advanced_nglview_usage.html

**Comment by wangenau** [comment]
Alright, I will close this issue then.
I will convert the notebook to html and use that html instead of linking to the gitlab render.
Thanks a lot!
