### ISSUE TITLE
How to use imageio-ffmpeg to replace MovieMaker?

### ISSUE THREAD

**Issue by johnnytam100** [nglviewer/nglview#1028]
I tried to import `MoveMaker` but

![image](https://user-images.githubusercontent.com/51283097/184366742-9053adb8-cdeb-474c-8be8-19952d2444c1.png)

So I have also done `! pip install imageio-ffmpeg`

Then, may I know how to use `imageio-ffmpeg` to replace `MovieMaker`?

Thank you!

**Comment by hainm** [comment]
Hi @johnnytam100 

Can you try one of below ways:
- After `! pip install imageio-ffmpeg` try to restart the notebook (to reload the change) and try again
- Use older version (and restart the notebook too)
```
pip install moviepy==0.2.2.11
pip install imageio==1.6
```

**Comment by johnnytam100** [comment]
Hi @hainm , it worked!

However, when I tried to `movie.make()` the rendering didn't even start and the cell just finished its execution.

![image](https://user-images.githubusercontent.com/51283097/184497189-0045a122-c904-46cf-a39f-dfa52d7cf457.png)

Do you know how to make it render?

Thank you!

**Comment by johnnytam100** [comment]
Um.. I tried adding this and worked:

```
from google.colab import output
output.enable_custom_widget_manager()
```

Thanks!

**Comment by hainm** [comment]
Yeah, and you have to display the view first before making the gif.
