### ISSUE TITLE
nglview often does not display water molecules

### ISSUE THREAD

**Issue by ajerschow** [nglviewer/nglview#1029]
In many cases when selecting a residue and surrounding water molecules with mdanalysis, nglview does not display the water molecules, even though the water is in the selection. Interestingly, when I select a single or two water molecules, they are displayed, but not if there are three. Is this a known issue?

nglview: v 2.7.7
ipywidgets: v 7.6.3

Thank you

**Comment by hainm** [comment]
@ajerschow  Can you please post exact code you've been trying?
When you're saying "selecting", do you mean doing that interactively or via command?

**Comment by ajerschow** [comment]
here are the commands (should I share the trajectory also?):

```
import nglview as nv
import matplotlib.pyplot as plt
import MDAnalysis
import numpy as np
import matplotlib.pyplot as plt
import re

fpath = 'set path to tracectory'
topfname = 'set topology file name'
trajfname = 'set trajectory file name'

u = MDAnalysis.Universe(fpath+topfname, fpath+trajfname)
```

(1) this part here works as expected (showing 2 water molecules):

```
sel = u.select_atoms('resid 10:11')
print(sel.atoms)
nv.show_mdanalysis(sel)
```

`print(sel)` shows the following:
`<AtomGroup [<Atom 58: O of type OW of resname WAT, resid 10 and segid SYSTEM>, <Atom 59: H1 of type HW of resname WAT, resid 10 and segid SYSTEM>, <Atom 60: H2 of type HW of resname WAT, resid 10 and segid SYSTEM>, <Atom 61: O of type OW of resname WAT, resid 11 and segid SYSTEM>, <Atom 62: H1 of type HW of resname WAT, resid 11 and segid SYSTEM>, <Atom 63: H2 of type HW of resname WAT, resid 11 and segid SYSTEM>]>`

(2) and this here does not work (shows empty canvas):

```
sel = u.select_atoms('resid 10:13')
print(sel)
nv.show_mdanalysis(sel)
```

`print(sel)` shows the following:
`<AtomGroup [<Atom 58: O of type OW of resname WAT, resid 10 and segid SYSTEM>, <Atom 59: H1 of type HW of resname WAT, resid 10 and segid SYSTEM>, <Atom 60: H2 of type HW of resname WAT, resid 10 and segid SYSTEM>, ..., <Atom 67: O of type OW of resname WAT, resid 13 and segid SYSTEM>, <Atom 68: H1 of type HW of resname WAT, resid 13 and segid SYSTEM>, <Atom 69: H2 of type HW of resname WAT, resid 13 and segid SYSTEM>]>`

**Comment by hainm** [comment]
can you try
```
view = nv.show_mdanalysis(sel)
view.add_line() # or view.add_licorice()
view
```

**Comment by hainm** [comment]
Alternative, try not to use `u.select_atoms` but using `NGL` selection: https://nglviewer.org/ngl/api/manual/usage/selection-language.html

```
view = nv.show_mdanalysis(u)
view.clear()
view.add_licorice(<...>)
view
```

**Comment by ajerschow** [comment]
Thank you, just tried this. There seems to be the same problem: I can display the isolated residues, e.g. 

this works:
`view.add_licorice('10')`

this does not work (only displaying one water:
`view.add_licorice('10,11,12')`

**Comment by hainm** [comment]
Please attach a pdb file. Thanks.

**Comment by ajerschow** [comment]
Please find it attached. prmtop + inpcrd 
`u = MDAnalysis.Universe('ADP.prmtop', 'ADP.inpcrd')`
[Archive.zip](https://github.com/nglviewer/nglview/files/9339783/Archive.zip)

**Comment by hainm** [comment]
thanks @ajerschow, I can reproduce the issue. Let me play with this a bit more before drawing any conclusion.

**Comment by Fuzz-Muffin** [comment]
I'm have a similar issue, water molecules are not visible but everything else is fine. Using nglview with MDAnalysis 'select_atoms' commands.

- MDAnalysis           2.3.0
- jupyterlab              3.5.0
- ipywidgets             7.7.2
- nglview                  3.0.3

**Comment by hainm** [comment]
> thanks @ajerschow, I can reproduce the issue. Let me play with this a bit more before drawing any conclusion.

I've filed a case in NGL here: https://github.com/nglviewer/ngl/issues/1013

**Comment by hainm** [comment]
@ajerschow  sorry for super long (years) delay in responding to you.
In case you're still interested, you can use below to display the water molecules.

```
view.center()
view.add_ball_and_stick('water')
```

**Comment by ajerschow** [comment]
Thank you!
Alexej
