### ISSUE TITLE
How to render movie in a standalone python script through terminal by MovieMaker?

### ISSUE THREAD

**Issue by johnnytam100** [nglviewer/nglview#1030]
Currently, I successfully rendered movie in Google Colab notebook like this:

![image](https://user-images.githubusercontent.com/51283097/184829976-6e88a250-bbd9-4408-909e-9f02d29a3fca.png)

However, the whole script when copied to a standalone python script and run through the terminal, it didn't work.

Any idea how to make it work?

Thank you!

**Comment by johnnytam100** [comment]
Hi @hainm ! Thanks for the advice again.
Then I am curious if you know a way of rendering movie in a loop, like this but doesn't work:

```
from google.colab import output
output.enable_custom_widget_manager()
import pytraj as pt
import nglview as nv
import mdtraj as md
from nglview.contrib.movie import MovieMaker
import MDAnalysis as mda
import glob

filepath_list = []

for filepath in glob.glob("./test_gromacs/*best*/"):
  filepath_list.append(filepath)

filepath_list.sort()

filepath_list_format = [i.split('/')[2] for i in filepath_list]

for filepath1, filepath2 in zip(filepath_list, filepath_list_format):

    tpr_path = filepath1 + 'protein_fit.tpr'
    xtc_path = filepath1 + 'protein_fit.xtc'
    
    u = mda.Universe(tpr_path, xtc_path)
    u.transfer_to_memory(step=10)
    view = nv.show_mdanalysis(u.atoms)

    view

    movie = MovieMaker(view, fps=10, in_memory=True, output= filepath2 + '.gif')
    movie.make()
```

**Comment by hainm** [comment]
hi @johnnytam100 

Can you please try to create a list of views first, then display each of them, then call moving making for each?

<img width="768" alt="image" src="https://user-images.githubusercontent.com/4451957/185530327-c39c4a21-7eb9-476c-8457-5bfab5f83a3f.png">
