### ISSUE TITLE
Remove reference backbone from movie

### ISSUE THREAD

**Issue by johnnytam100** [nglviewer/nglview#1031]
I'm sorry for raising a question again.

As I make a movie from a trajectory, the movie also includes the reference backbone (the topology?).

Is there any way to remove the reference backbone?

![ezgif com-gif-maker](https://user-images.githubusercontent.com/51283097/185034071-a5186503-bf31-4196-a2fd-4fe0754ddd04.gif)

My script is like this:

```
from google.colab import output
output.enable_custom_widget_manager()
import pytraj as pt
import nglview as nv
import mdtraj as md
from nglview.contrib.movie import MovieMaker
import MDAnalysis as mda

traj_filename = './example_traj/protein_fit.xtc'
pdb_filename = './example_traj/protein_fit.tpr'

u = mda.Universe(pdb_filename, traj_filename)
u.transfer_to_memory(step=10)
view = nv.show_mdanalysis(u)

view
```

then

```
movie = MovieMaker(view, fps=10, in_memory=True, output='peptide_raw.gif')
movie.make()
```

**Comment by hainm** [comment]
Try to avoid colab for now, using traditional notebook or lab.
I filed the case several months ago: https://github.com/googlecolab/colabtools/issues/2853#issuecomment-1171699299

**Comment by hainm** [comment]
Close this issue since there is nothing we can do now.

**Comment by kimjc95** [comment]
I made a quick workaround.
You can turn off the default representation and then add the representation for your molecules.

u = mda.Universe(pdb_filename, traj_filename)
u.transfer_to_memory(step=10)
view = nv.show_mdanalysis(u, defaultRepresentation=False)
view.add_cartoon("protein")
view

**Comment by hainm** [comment]
> I made a quick workaround. You can turn off the default representation and then add the representation for your molecules.
> 
> `u = mda.Universe(pdb_filename, traj_filename)` `u.transfer_to_memory(step=10)` `view = nv.show_mdanalysis(u, defaultRepresentation=False)` `view.add_cartoon("protein")` `view`

@kimjc95 You might also want to add `view.center()` too because the default representation is not used.

**Comment by kimjc95** [comment]
@hainm You are right! I missed that part. By the way, how do I recreate the default representation of nucleic acids? I tried add_cartoon("nucleic"), and it did show the phosphate backbone as ribbons, but did not show the bases as sticks.

**Comment by hainm** [comment]
> @hainm You are right! I missed that part. By the way, how do I recreate the default representation of nucleic acids? I tried add_cartoon("nucleic"), and it did show the phosphate backbone as ribbons, but did not show the bases as sticks.

@kimjc95 I admit I don't know the answer, but here is the code in `NGL` (which nglview is using under the hood) for default one: https://github.com/nglviewer/ngl/blob/417581fa92971fe98560b2d0e1ac9d00046b7ba6/src/stage/stage.ts#L291-L418

**Comment by kimjc95** [comment]
@hainm Thanks for the link. It came out to be add_simplified_base("nucleic") .
