### ISSUE TITLE
How to keep the play button always showing in a traj view

### ISSUE THREAD

**Issue by dou-du** [nglviewer/nglview#1038]
When we use nglview to show a traj file, the play button will be hidden when the mouse is outside the visualizer. Is it possible to keep the play button (with the slider) always showing in the view?

Otherwise, is it possible to disable it so we can use the ipywidget play and slider widget? Thanks!

**Comment by hainm** [comment]
> Is it possible to keep the play button (with the slider) always showing in the view?

Please execute below:
```javascript
view._js("""
this.mouseOverDisplay('block')
var container = this.stage.viewer.container
var that = this
container.addEventListener('mouseout', function(e) {
          that.mouseOverDisplay('block')
      }, false);
""")
```

> Otherwise, is it possible to disable it so we can use the ipywidget play and slider widget? Thanks! 
```javascript
view._js("""
this.mouseOverDisplay('none')
var container = this.stage.viewer.container
var that = this
container.addEventListener('mouseover', function(e) {
          that.mouseOverDisplay('none')
      }, false);
""")
```
>  ipywidget play and slider widget

FYI: we also have `view._iplayer` too.

Cheers
