### ISSUE TITLE
Colorizing CIF-data atoms

### ISSUE THREAD

**Issue by CRTejaswi** [nglviewer/nglview#1039]
- Version report

```
3.0.3
7.7.1
```

I'm getting white blocks of atoms/bonds. How may I colorize them?

![image](https://user-images.githubusercontent.com/24400066/202047701-a9cf54cf-d559-4208-835f-780e7a329b9d.png)

**Comment by hainm** [comment]
Do you have a public example to reproduce?

**Comment by CRTejaswi** [comment]
Sure. I'm sharing the notebook & cif files I've used: [run.zip](https://github.com/nglviewer/nglview/files/10047724/run.zip)

**Comment by hainm** [comment]
> @hainm Sure. I'm sharing the notebook & cif files I've used: [run.zip](https://github.com/nglviewer/nglview/files/10047724/run.zip)

Dear @CRTejaswi, I am sorry for my late reply.
I don't know "why" but you can use `atomicindex` for color_scheme like below:

```
import nglview as ng

CRYSTAL = 'V4GaSe8'
# FeCoB, MgO, Al2O3, GaV4Se8_55K, V4GaSe8 

# visualize crystal structure
view = ng.show_structure_file(f'datasets/{CRYSTAL}.cif', default=False)
view._remote_call('setSize', args=['','600px'])
view.camera = 'orthographic'
view.add_unitcell()
view.center()
view.add_ball_and_stick(color_scheme='atomindex')
view
```

<img width="851" alt="image" src="https://user-images.githubusercontent.com/4451957/206934914-9e688ffe-787f-496c-8677-5fe927e5da87.png">

**Comment by hainm** [comment]
I've filed a case in `NGL` repo to ask for help: https://github.com/nglviewer/ngl/issues/950

**Comment by CRTejaswi** [comment]
Thank you!
