### ISSUE TITLE
show_html function not working, nglview-js-widget.js missing/404 error

### ISSUE THREAD

**Issue by Raman-Shakya** [nglviewer/nglview#1046]
## Description
I am experiencing an issue with the show_html function in nglview. When I call this function to display an NGL view in an HTML page, I am getting an error message that the nglview-js-widget.js file is missing or returns a 404 error. As a result, the NGL view is not displayed.

## Expected behavior
The show_html function should display the NGL view in an HTML page without any errors or missing files.

## Actual behavior
The show_html function displays an error message that the nglview-js-widget.js file is missing or returns a 404 error, and the NGL view is not displayed.

## Additional information
I am using nglview version 3.0.3.
I am using ipywidget version 7.7.2

## Code examples
```python
import nglview

view = nglview.demo()
nglview.write_html('temp.html', [view])
```

## Browser Console Output
![image](https://user-images.githubusercontent.com/77957168/221423970-4ecf5a63-4915-44ea-850a-25a5892ff57c.png)

> if I am missing something please let me know

**Comment by hainm** [comment]
@Raman-Shakya You need to display the `view`first

1st cell
```
view = nglview.demo()
view
```

2nd cell
```
nglview.write_html('temp.html', [view])
```

**Comment by Raman-Shakya** [comment]
Oo thank you! it worked!
