### ISSUE TITLE
Facing an issue to view the structure of a model by using 'nv.show_biopython(structure)'

### ISSUE THREAD

**Issue by Surajit-1108** [nglviewer/nglview#1047]
nv.show_biopython(structure) is not working in jupyter notebook. It is continuously showing 'I/O operation on closed file'. Please go through the link for further [references.](url)

[
![Protein-Drug interaction project](https://user-images.githubusercontent.com/118954128/223895259-bbef55fd-c3c2-497d-8501-c5b310a6368d.jpg)
](url)

**Comment by hainm** [comment]
Dear @Surajit-1108: for now, please try the suggestion in StackOverflow page here ( try to downgrade your biopython version): https://stackoverflow.com/questions/74737766/file-i-o-error-using-nglview-show-biopythonstructure

**Comment by Surajit-1108** [comment]
Hello Hai Nguyen,
 Thank you for your response. I will try to do it as per your instructions.


Thanks & Regards,
Surajit Bal
