### ISSUE TITLE
nv.demo() does not show anything

### ISSUE THREAD

**Issue by GoranM88** [nglviewer/nglview#1048]
Hi!

In Jupyter notebook I tried the following:
     import nglview as nv
     view = nv.demo()
     view

After running "view" nothing happens. I get the following error message in Ubuntu terminal: 
[W 11:28:00.611 NotebookApp] 404 GET /notebooks/a4c733ec4baef9ad3896d4e34a8a5448.png (127.0.0.1): file or directory does not exist: 'a4c733ec4baef9ad3896d4e34a8a5448.png'
		404 GET /notebooks/a4c733ec4baef9ad3896d4e34a8a5448.png (127.0.0.1) 32.800000ms referer=http://localhost:8888/notebooks/Untitled.ipynb?kernel_name=python3

In Chrome console I see this:
![image](https://user-images.githubusercontent.com/6008175/224314789-d7e88ee2-7338-465f-b31c-099bdf427e74.png)

I went through all the posts where a similiar issue has been raised. So far I have tried every suggestion described, however I still can't get it to work. 

1.) These are the packages that I have installed in my conda environment:
		-nglview: 3.0.3
		-ipywidgets: 7.6.5
		-ipython: 8.11.0
		-notebook: 6.5.2 
		-notebook-shim: 0.2.2
		-jupyter lab: 3.6.1
		-jupyterlab_widgets: 3.0.5
		-widgetsnbextension: 3.5.2
		-node.js: v18.14.0

2.) I have jupyter notebook extensions installed and enabled:
	Known nbextensions:
		config dir: /opt/anacodna3/envs/mdaenv/etc/jupyter/nbconfig
		  notebook section
		    jupyterlab-plotly/extension  enabled
		    - Validating: OK
		    nglview-js-widgets/extension  enabled
		    - Validating: OK
		    jupyter-js-widgets/extension  enabled
		    - Validating: OK

3.) I don't have the folder: $HOME/.local/share/jupyter/nbextensions/ngl-js-widgets/

4.) I tried both Chrome and Edge.

When I type !pip show nglview-js-widgets I get: WARNING: Package(s) not found: nglview-js-widgets. How is this possible given that nglview-js-widgets/extension is enabled?

I would really appreciate any help to get this issue solved.

Thank you,
Goran

**Comment by hainm** [comment]
hi @GoranM88,

Unfortunately I don't know how to resolve your issue. This is the first time I see this type of error message.

> When I type !pip show nglview-js-widgets I get: WARNING: Package(s) not found: nglview-js-widgets. How is this possible given that nglview-js-widgets/extension is enabled?

Because that extension is already included in `nglview` itself.z
