### ISSUE TITLE
jupyterlab chokes on colorbrewer JS shipped with nglview

### ISSUE THREAD

**Issue by ltalirz** [nglviewer/nglview#1051]
- Version report: nglview 3.0.3, ipywidgets 7.7.3.

When using nglview to create isosurfaces from cube files in a jupyterlab environment, we find the following error in the Javascript console (Edge 111.0.1661.51):
```
ErrorEvent {isTrusted: true, message: 'Uncaught SyntaxError: Function statements require a function name', filename: 'blob:[https://.../017a20b1-530c-4508-b3cb-20824f9601c2'](https://.../017a20b1-530c-4508-b3cb-20824f9601c2%27), lineno: 51, colno: 1, …}
```
This prevents the isosurfaces from being shown.

This error originates from the colorbrewer javascript file https://github.com/nglviewer/nglview/blob/master/nglview/staticlab/static/421.04c3327cf7f16704c3b2.js

which contains the following line:

```javascript
function(){return[[0,4,4,4,2,0,0,0....
``` 

I don't know enough about javascript to know whether this was ever legal - in any case, it does not seem to be legal now.

In our particlar case, this function was actually not used, so we were able to fix the problem by giving it a random name, e.g.

```javascript
function cb(){return[[0,4,4,4,2,0,0,0....
``` 

I suspect the unnamed function is actually not used anywhere in the code and could be deleted (?)

**Comment by ltalirz** [comment]
P.S. Now that support for ipywidgets 8 is merged, would be great to get this bugfix in before the next release

**Comment by hainm** [comment]
hi @ltalirz, what's the exact commands did you use and which lab is it?

**Comment by hainm** [comment]
Close since there is no interest from user to follow up.
