### ISSUE TITLE
Quarto support

### ISSUE THREAD

**Issue by pschmidtke** [nglviewer/nglview#1053]
Hey,

I manage to run nglview in a jupyter notebook just fine & can customize a lot of things, which is great. However, I'd like to use quarto & render notebooks to html pages, and there the widgets are not displayed. 

Does somebody have any quarto version of nglview working ? I mean the same level of customization support as in nb, not the alias that allows just to pull a structure & display it. I really need to create representations for specific residues, use selection syntax etc ... 

Thanks in advance!

**Comment by hainm** [comment]
I guess no one has the experience. I am go ahead closing.
