### ISSUE TITLE
nglview run error

### ISSUE THREAD

**Issue by sekhwal** [nglviewer/nglview#1054]
I am trying to run nglview with the following command "import nglview as nv" but it show an error.

error::::
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/tmp/ipykernel_8977/1899191847.py in <cell line: 1>()
----> 1 import nglview as nv

~/anaconda3/lib/python3.9/site-packages/nglview/__init__.py in <module>
      2 
      3 # for doc
----> 4 from . import adaptor, datafiles, show, widget
      5 from ._version import get_versions
      6 from .adaptor import *

~/anaconda3/lib/python3.9/site-packages/nglview/show.py in <module>
     11                       RdkitStructure,
     12                       TextStructure)
---> 13 from .widget import NGLWidget
     14 
     15 __all__ = [

~/anaconda3/lib/python3.9/site-packages/nglview/widget.py in <module>
     17 import traitlets
     18 
---> 19 from . import color, interpolate
     20 from .adaptor import Structure, Trajectory
     21 from .component import ComponentViewer

~/anaconda3/lib/python3.9/site-packages/nglview/color.py in <module>
    112 
    113 
--> 114 ColormakerRegistry = _ColormakerRegistry()

~/anaconda3/lib/python3.9/site-packages/nglview/base.py in getinstance()
      8     def getinstance():
      9         if cls not in instances:
---> 10             instances[cls] = cls()
     11         return instances[cls]
     12     return getinstance

~/anaconda3/lib/python3.9/site-packages/nglview/color.py in __init__(self, *args, **kwargs)
     45         try:
     46             get_ipython() # only display in notebook
---> 47             self._ipython_display_()
     48         except NameError:
     49             pass

~/anaconda3/lib/python3.9/site-packages/nglview/color.py in _ipython_display_(self, **kwargs)
     52         if self._ready:
     53             return
---> 54         super()._ipython_display_(**kwargs)
     55 
     56     def __repr__(self):

AttributeError: 'super' object has no attribute '_ipython_display_'

**Comment by hainm** [comment]
@sekhwal  Please see this thread: https://github.com/nglviewer/nglview/issues/1052
