### ISSUE TITLE
ACE and NME have different representations from the rest of the molecule

### ISSUE THREAD

**Issue by jessicaflowers** [nglviewer/nglview#1061]
I am trying to visualize a tripeptide pdb, but the representations are acting up. To give context, I took a dipeptide pdb file and capped either end with ACE and NME, respectively. (so 4 residues total, around 50 atoms). Here is my code:

view = nv.show_file('PED00004_8_9.pdb') 
view.add_representation("licorice")
view

This works, but there is a slight issue. First, the ACE and NME added sections have a completely different representation from the rest of the peptide. They are fatter, ball and stick representations whereas the center 2 residues are licorice. 

My initial guess was it's possible that nglview is trying to auto-detect which residues are not standard amino acids and making them fat. I have looked into solving this problem, but have not had much luck.

Thanks!

<img width="774" alt="Screen Shot 2023-05-23 at 8 06 56 PM" src="https://github.com/nglviewer/nglview/assets/108426511/47e354a2-f712-463e-8742-7fbc70946304">

**Comment by Renws** [comment]
May I ask, what method did you use to add ACE and NME, software or other scripts? Thanks.

**Comment by 5dwdvd** [comment]
@jessicaflowers You might have figured it out by now, but have you tried clearing the representations with `view.clear()` before adding licorice?


```python
import nglview
from rdkit.Chem import AllChem
from rdkit import Chem

# ACE-Val-Phe-NME
dipeptide = Chem.MolFromSmiles(
    'CNC(=O)[C@H](Cc1ccccc1)NC(=O)[C@@H](NC(C)=O)C(C)C'
    )
dipeptide = Chem.AddHs(dipeptide)
AllChem.EmbedMolecule(dipeptide)
view = nglview.show_rdkit(dipeptide)
view.clear()
view.add_representation("licorice")
view
```

<img width="341" alt="image" src="https://github.com/nglviewer/nglview/assets/83641414/dd90b485-f522-448a-b459-cb98901d2adf">

**Comment by jessicaflowers** [comment]
the view.clear() seems to have worked, thank you!
