### ISSUE TITLE
Unable to run nglview in my browsers

### ISSUE THREAD

**Issue by Ash100** [nglviewer/nglview#1076]
Hello, I am sorry for asking such a basic question here. I am trying to run nglview in Jupyter Notebook using Chrome. I am able to run all the scripts successfully without an error, but still unable to visualize anything. Below are the scripts, I tried. 
`!pip install Bio`
`!pip install nglview`
`!pip install "ipywidgets>=7,<8"`
`from google.colab import output
output.enable_custom_widget_manager()

import ipywidgets as widgets
from IPython.display import display
import os
import sys
from urllib.request import urlretrieve
import Bio
from Bio import PDB
from Bio import SeqIO, SearchIO, Entrez
from Bio.Seq import Seq
import pylab
import urllib
import pandas as pd
import nglview as nv
from collections import Counter
from Bio.PDB import PDBParser,MMCIFParser`
`urllib.request.urlretrieve('https://files.rcsb.org/download/4I5S.pdb','4I5S.pdb')`
`structure = PDB.PDBParser().get_structure("4I5S", "4I5S.pdb")`
`view=nv.show_biopython(structure)
view`

I think I am so how unable to successfully enable the third part widgets in chrome, but it is what i am thinking. 
I would be thankful, if someone can help fix my issue- i suppose won't be that bigger.
Best Regards, 
Ash

**Comment by hainm** [comment]
hi @Ash100, can you try to use `nglview` v3.0.6 instead? 
There is something wrong with the latest v3.0.7.

**Comment by hainm** [comment]
I've released 3.0.8. Please try again.

**Comment by Ash100** [comment]
Thank you so much. At least I am able now to call nglview but still, I am unable to turn on the gui = True. At times it stays silent while other times, it is asking to enable widgets, though they are enabled and I am not seeing that warning on importing nglview as nv.

**Comment by hainm** [comment]
Can you please capture your screen?

May be try

view = nv.demo()
view.gui_style = “ngl”
view

first.

**Comment by Ash100** [comment]
view.gui_style = 'ngl'  --- it works fine and generates GUI controls
view = nv.demo()   ---- generates warning message from code snipet "enable_custome_widget_manager
nv.show_biopython(structure, gui=True) ---- visualize structure with out GUI controls

I am trying to drop these three screenshots from the same notebook below
![1](https://github.com/nglviewer/nglview/assets/7489513/562f794a-2e19-4491-b782-bb126b29cad3)
![2](https://github.com/nglviewer/nglview/assets/7489513/96e49203-f562-4508-af65-9f8a0319855e)
![3](https://github.com/nglviewer/nglview/assets/7489513/546c4218-dccf-4ea0-bd76-f2fb8f2a42d2)

**Comment by hainm** [comment]
Thanks. It seems like it’s a problem with google colab. You can try again
with traditional notebook in your computer.

**Comment by Ash100** [comment]
Sure. Thank you @hainm for your support. In fact, the problem is solved. You can close the issue.
