### ISSUE TITLE
Display NGLViewer when kernel is running

### ISSUE THREAD

**Issue by GregorySchwing** [nglviewer/nglview#1079]
- Question about usage? I am unable to see the view unless I stop the kernel.  It simple says "nothing" and a blank white screen.  then when I stop the kernel, it shows.  I can bypass this by running each cell individually, but I'd rather not.

- Version report

```bash
print(nglview.__version__)'
3.0.8
print(ipywidgets.__version__)'
7.7.2

```

**Comment by hainm** [comment]
Thanks for reporting. It's weird. Noted.

**Comment by hainm** [comment]
https://github.com/nglviewer/nglview/issues/901#issuecomment-1793587615

I guess this is the full description?

**Comment by hainm** [comment]
[GregorySchwing](https://github.com/GregorySchwing)
```
I have a working installation of nglview using jupyter lab. My problem is i'd like to be able to "Restart Kernel and Run all Cells" and see the nglview as the cells are run, however, the views aren't displayed until after all the kernels finish or I stop the kernel. Is there anyway to get my desired behavior?
```

**Comment by GregorySchwing** [comment]
> [GregorySchwing](https://github.com/GregorySchwing) `I have a working installation of nglview using jupyter lab. My problem is i'd like to be able to "Restart Kernel and Run all Cells" and see the nglview as the cells are run, however, the views aren't displayed until after all the kernels finish or I stop the kernel. Is there anyway to get my desired behavior?`

yes that is the full description

**Comment by GregorySchwing** [comment]
although this was actually done in notebook not lab

**Comment by hainm** [comment]
@GregorySchwing I have been thinking about this and I think it's not about `nglview` but about Python in general. When clicking `"Restart Kernel and Run all Cells" `, the python codes will be run in a single thread and blocks other threads to run. So the run must be finished to display anything. 

(My educated guess).
