### ISSUE TITLE
nv.write_html doesn't show any molecule.

### ISSUE THREAD

**Issue by mmmekr** [nglviewer/nglview#1080]
my ver
OS: linux
![picC](https://github.com/nglviewer/nglview/assets/149999747/d796a344-fe63-491b-8945-e8e72079eb8e)

Hi all.

I created a conda env with python 3.11, and installed nglview with pip.
With the environment, I can see molecule in notebook, but I cannot see any molecules in html files.
![picA](https://github.com/nglviewer/nglview/assets/149999747/62023cae-c1e2-4fd4-a360-d22fd699ece7)

The html file said that
![picB](https://github.com/nglviewer/nglview/assets/149999747/9072a0b9-523f-472c-90e8-da69db258ee4)

I tryied an environment with python 3.9,
installing with conda, 
jupyter-nbextension enable --py --user widgetsnbextension, 
jupyter-nbextension enable --py --user nglview (both ok), 
rm -rf ~/anaconda3/envs/test/share/jupyter/nbextensions/nglview-js-widgets/
conda install -c javascript nodejs, 
cd js + npm install .

**Comment by hainm** [comment]
Thank you for your report. I've noted.

**Comment by mmmekr** [comment]
OK, thanks for your reply.
So, could I solve this problem with an older version?
I actually tried the old one (nglview==2.7.1 and ipywidgets=5.7.1), but it didn't work.
If you have any ideas, please let me know.

**Comment by hainm** [comment]
dear @mmmekr I could not reproduce the issue on my macbook, chrome + python 3.10

<img width="776" alt="image" src="https://github.com/nglviewer/nglview/assets/4451957/7bb451cd-549e-4eaf-a1eb-88363da16c4b">

The html shows the structure when I open it

**Comment by mmmekr** [comment]
@hainm 
Thanks!!
When I created an environment with notebook==7.0.6, it could create a valid html file!!!
![pica](https://github.com/nglviewer/nglview/assets/149999747/6751e548-60fc-49db-a60b-9b17bcecc4a7)
(html file)
![picb](https://github.com/nglviewer/nglview/assets/149999747/687ef93d-ad7b-4eb5-9c1f-d48174420aaa)

However, when I tried an another code to show my AF2 predectied PDB files, It didn't create good html files.
![pic](https://github.com/nglviewer/nglview/assets/149999747/fb339dbc-41b9-43fd-a9f5-6c1b6fa00ae1)

I tried rm -rf ~/anaconda3/envs/(envs)/share/jupyter/nbextensions/nglview-js-widgets, jupyter-nbextension enable --py --user widgetsnbextension, and jupyter-nbextension enable --py --user nglview, but It didn't work.

When I use an environment with notebook==6.5.4, It showed valid views but created invalid html files.
![picc](https://github.com/nglviewer/nglview/assets/149999747/fd78277c-9465-42ec-b783-14941d5c3e22)
![picd](https://github.com/nglviewer/nglview/assets/149999747/a69ddd03-3752-409f-8b4c-50e5d63f3277)

**Comment by hainm** [comment]
Dear @mmmekr : can you please try `nv.show_structure_file` instead? `show_structure_file` will read the content of pdb into string and will be saved in the html file. Let me know if that works.

**Comment by mmmekr** [comment]
@hainm, Thanks you for your advice!
It has worked!
I really appreciate you.

**Comment by hainm** [comment]
great. You're welcome, @mmmekr 

Hai
