### ISSUE TITLE
Load MD trajectory with controls

### ISSUE THREAD

**Issue by pguillem** [nglviewer/nglview#1084]
Hello,

Is there an example html/js template that I could use to load an MD trajectory into a viewport?. Ideally, just providing a path to an XTC traj and pdb topology. Maybe even have some controls available (decimation, representations, etc), like the ones in the examples?

Is MDSrv necesary to move across frames on demand? or the viewport loads the entire trajectory?

Thanks in advance.
Pedro

**Comment by hainm** [comment]
Dear @pguillem `nglview` is for Jupyter notebook. If you wants to look at html/js, please ask the question in the `NGL` repo: https://github.com/nglviewer/ngl/issues 

cheers

**Comment by pguillem** [comment]
Thanks. Will do
