### ISSUE TITLE
Compatibility with jupyterlab 4

### ISSUE THREAD

**Issue by mkrompiec** [nglviewer/nglview#1088]
Is it possible to use nglview with jupyterlab 4? I would like to avoid downgrading to jupyterlab 3.
`nglview.demo() `gives me `Loading widget...` and no other output. Tried with the latest release and the main branch from git. Versions 3.0.3 and 3.0.5 give me `Error displaying widget`.

- Version report

```bash
python -c 'import nglview; print(nglview.__version__)'
python -c 'import ipywidgets; print(ipywidgets.__version__)'
3.0.8
7.7.3
```

**Comment by hainm** [comment]
Dear @mkrompiec: noted for the issue. I don't have the answer yet (probably No, we need to update code to support).

**Comment by mkrompiec** [comment]
Thanks! Looking forward to the fix :)

**Comment by mkrompiec** [comment]
However, this issue https://github.com/nglviewer/nglview/issues/1082 seems to suggest that it should work with JupyterLab 4...

**Comment by hainm** [comment]
I've tested with below env
```
mamba create -n lab4 python=3.10 jupyterlab=4 -c conda-forge
source activate lab4
mamba install nglview -c conda-forge
```

**Comment by mkrompiec** [comment]
Thanks! This solves the problem!
