### ISSUE TITLE
How to load both surface point and protein at the same time? 

### ISSUE THREAD

**Issue by smiles724** [nglviewer/nglview#1089]
Hi, I want to change the color of the loaded protein. However, it seems this commend ' view.add_representation('cartoon', color='blue')'  is not working. Can you please give me some help? Thanks 

![image](https://github.com/nglviewer/nglview/assets/39299863/fe678c0c-55a1-4fe8-a12f-b1c23e2c4fa0)

![image](https://github.com/nglviewer/nglview/assets/39299863/91ad684c-97e9-4f39-9bca-14e6b0439c99)

**Comment by hainm** [comment]
@smiles724 Please try to add `component=1` to your `add_representation`, the default is the first component and you're trying to update 2nd one.

**Comment by smiles724** [comment]
> @smiles724 Please try to add `component=1` to your `add_representation`, the default is the first component and you're trying to update 2nd one.

Thanks for your reply!
