### ISSUE TITLE
custom rgb color

### ISSUE THREAD

**Issue by Dan-Burns** [nglviewer/nglview#1090]
Hi,

If I try to assign a color to a shape, I end up with something different.  Typically it's white or cyan.

Here's an example where I try to apply a green color.

![image](https://github.com/nglviewer/nglview/assets/58605062/d087f9c2-8af5-4007-80f9-474e494e1d7d)

Thank you for your help.

Dan

- Version report
nglview = 3.0.3
ipywidgets = 7.6.0

**Comment by hainm** [comment]
hi @Dan-Burns 

Please use RGB code. e.g: for that green color, use `[0, 128, 0]`

<img width="702" alt="image" src="https://github.com/nglviewer/nglview/assets/4451957/50abd721-1dcf-4376-9979-6efb832cbf3f">

**Comment by Dan-Burns** [comment]
Thanks @hainm.  I take it that only a subset of colors can be depicted?
