### ISSUE TITLE
slow shape.add_cylinder

### ISSUE THREAD

**Issue by Dan-Burns** [nglviewer/nglview#1093]
I'm adding cylinders in a loop and it seems to be very slow.  On the order of a dozen seconds to add several dozen cylinders.
Is there a way to speed this up?

**Comment by hainm** [comment]
I don't know if there is a way in `nglview`, please ask `NGL` developers here. They might give you some hint in javascript and you can execute custom JS code via `view._js`

https://github.com/nglviewer/ngl/issues
