### ISSUE TITLE
Component handling not working properly under Google Colab

### ISSUE THREAD

**Issue by mnmelo** [nglviewer/nglview#1094]
- Version report
nglviewer: 3.0.8 in both Jupyter and Colab
ipywidgets: 8.1.1 in both Jupyter and Colab

I've got diverging results when trying to show two simultaneous structures (a protein and, overlayed, its Martini 3 CG transformation) in Jupyter Lab and in Google Colab.

In Jupyter all seems as I want:
![jupyter](https://github.com/nglviewer/nglview/assets/11721337/7615d37b-1877-4d2e-926f-9aedee2844fc)

In Colab, however, the second component is ignored and the ball_and_stick rendering is applied to the first component:
![colab](https://github.com/nglviewer/nglview/assets/11721337/6b44c99b-e78a-4902-a306-fc6727e8f11b)

Refreshing the Colab page seems to fix this in some cases:
![colab_refresh](https://github.com/nglviewer/nglview/assets/11721337/a26fd5db-096a-4d0d-8808-fe722a4a49be)

Another possibly important aspect is that I must update ipywidgets from within Colab, and then can only restart the session, since a runtime restart loses changed files. Prior to update ipywidgets is version 7.7.1.

Help appreciated!
I attach the used structure files.
[structures.zip](https://github.com/nglviewer/nglview/files/13745729/structures.zip)

**Comment by hainm** [comment]
Dear @mnmelo: I am sorry to hear that, but (yeah, there is always a but), it's really up to google to fix the colab. It's out of `nglview`'s hand.

**Comment by mnmelo** [comment]
Of course. I was just wondering whether this could be an issue in how nglview/NGL handle the different environments.

**Comment by hainm** [comment]
I don't think so. IMO, if `nglview` works well for notebook and lab, it should be something else.

**Comment by hainm** [comment]
Close as "won't fix" since there is nothing I can do. colab needs to do something.
