### ISSUE TITLE
upgrade nglview so will work with ipywidgets 8 or greater?

### ISSUE THREAD

**Issue by scottwsides** [nglviewer/nglview#1095]
This issue has been mentioned before... eg that ipywidgets needs to be between 7.7.1-8 to work (meaning that 'import nglview' will not fail). I'm worried that if this continues that it will eventually stop working in jupyterlab. Are there plans to update nglview so that it will work with updated ipywidgets and jupyterlab?

**Comment by hainm** [comment]
hi @scottwsides 

Latest `nglview` already works well with lab and ipywidgets 8 (https://github.com/nglviewer/nglview/pull/1045) 
We made a release almost a year ago.

**Comment by scottwsides** [comment]
I just tested latest versions of ipywidgets, jupyterlab and nglview=3.0.8 and 'import nglview' fails with errors about _ipython_display

**Comment by hainm** [comment]
> I just tested latest versions of ipywidgets, jupyterlab and nglview=3.0.8 and 'import nglview' fails with errors about _ipython_display
> 
> Just triple checked and w/these deps 'import nglview' fails
> 
> * ipywidgets==8.0.6
> * nglview==3.0.4 (version mentioned in [Support ipywidgets v8 #1045](https://github.com/nglviewer/nglview/pull/1045)
> * jupyterlab=4.1.0b0
> 
> <img alt="Screen Shot 2024-01-08 at 4 12 51 PM" width="866" src="https://private-user-images.githubusercontent.com/13578795/295060372-d5f20205-5c13-4dfc-9139-19f06815002b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3NTk5NTUsIm5iZiI6MTcwNDc1OTY1NSwicGF0aCI6Ii8xMzU3ODc5NS8yOTUwNjAzNzItZDVmMjAyMDUtNWMxMy00ZGZjLTkxMzktMTlmMDY4MTUwMDJiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTA5VDAwMjA1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNmYjdkZmI0MmNmOGUxMjEwNGUxY2MzM2MxMzA1ZmVmMmU3ZDM3ZmU0NDZhOTk4MDQ0NTM4YzY0NDk4ZThiYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ygx5LcUWEnQ-lSPeMiQ7VUBl7PBwjw-T1BmRbilOj4w">
> I tried a couple of other >4 versions and no luck

I am getting lost here. there is no `__ipython_display__` error as you mentioned. 
If you click to show the Javascript error, what does the message say?

**Comment by hainm** [comment]
and what does the versions show in your notebook for nglview and ipywidgets

**Comment by hainm** [comment]
@scottwsides Or you can try my version here

<img width="1175" alt="image" src="https://github.com/nglviewer/nglview/assets/4451957/a7a7cbc8-5ada-4afc-bc55-5484d049cebd">

```
ipywidgets: 8.1.1
nglview: 3.0.8
```

**Comment by scottwsides** [comment]
Ok... so 
nglview==3.0.4 ipywidgets==8.0.6 jupyterlab>4 does NOT work
nglview==3.0.8 ipywidgets==8.1.1 jupyterlab>4 works. 

Thanks for the help. I would say you should document this somewhere. cheers,

**Comment by hainm** [comment]
> nglview==3.0.4 ipywidgets==8.0.6 jupyterlab>4 does NOT work
> nglview==3.0.8 ipywidgets==8.1.1 jupyterlab>4 works.

I see. I am not aware of this issue then.



> I would say you should document this somewhere. cheers,

Let's document there. :D

**Comment by hainm** [comment]
I've updated here: https://github.com/nglviewer/nglview/blob/master/README.md#released-version

**Comment by scottwsides** [comment]
Thanks for the help!
