### ISSUE TITLE
memory address error when rendering image from nglview

### ISSUE THREAD

**Issue by Fadelis98** [nglviewer/nglview#1097]
- Version report
python: 3.10.12
ipywidgets: 8.0.4
nglview: 3.0.8

BUG Description:

I'm trying to save this image generaged by nglview:
![1704786280639](https://github.com/nglviewer/nglview/assets/43640976/84ae99f5-1e31-4088-9d77-7718f730015b)
 
However, I got an empty file if I just save it in this cell, while it become correct out of that cell !

![image](https://github.com/nglviewer/nglview/assets/43640976/e0cee92b-d776-4798-b352-3135bdfd2139)

How to repeat:

[nglbug.zip](https://github.com/nglviewer/nglview/files/13870740/nglbug.zip)

You can repeat the minimun case in the notebook

**Comment by hainm** [comment]
Dear @Fadelis98 

It's an expected behavior due to asynchronous process. It's hard to explain so please just accept the fact. :D 

Please see this also: https://github.com/nglviewer/nglview/blob/master/docs/FAQ.md#how-to-make-nglview-view-object-write-png-file

**Comment by Fadelis98** [comment]
> Dear @Fadelis98
> 
> It's an expected behavior due to asynchronous process. It's hard to explain so please just accept the fact. :D
> 
> Please see this also: https://github.com/nglviewer/nglview/blob/master/docs/FAQ.md#how-to-make-nglview-view-object-write-png-file

LOL, it's actually an unexpected 'expected behavior', and thanks for your answer.

**Comment by hainm** [comment]
> > Dear @Fadelis98
> > It's an expected behavior due to asynchronous process. It's hard to explain so please just accept the fact. :D
> > Please see this also: https://github.com/nglviewer/nglview/blob/master/docs/FAQ.md#how-to-make-nglview-view-object-write-png-file
> 
> LOL, it's actually an unexpected 'expected behavior', and thanks for your answer.

yeah I know. I can't find any better way.
