### ISSUE TITLE
No widget renders on Jupyterlab 4.1

### ISSUE THREAD

**Issue by salotz** [nglviewer/nglview#1101]
I'm running a test on Jupyterlab with NGLView. I try to run the demo and I don't get any errors but it doesn't render anything.

Am I missing something?

![image](https://github.com/nglviewer/nglview/assets/7883146/1099ab91-e0e2-4975-9e20-01b7c59cf65e)

I'll add that I am running this through Jupyterhub on a kubernetes cluster. The Jupyterlab instance is running in this container image: quay.io/jupyter/minimal-notebook

**Comment by hainm** [comment]
hi @salotz 

I could not reproduce your issue in my laptop. 
So I guess it's something with your cluster setup (my random guess).

<img width="929" alt="image" src="https://github.com/nglviewer/nglview/assets/4451957/2de7e702-080c-415b-8a28-933a2174fb6d">

**Comment by salotz** [comment]
Thanks for trying out.

Could it be my browser/WebGL setup perhaps?

Info:

![image](https://github.com/nglviewer/nglview/assets/7883146/858266fb-ffbf-42e7-b227-1e0e26776e26)

![image](https://github.com/nglviewer/nglview/assets/7883146/3d6ddc55-753c-47eb-a69a-1d093d869e56)

The official Khronos page seems to think so (https://get.webgl.org/):

![image](https://github.com/nglviewer/nglview/assets/7883146/90225555-0e91-4bca-9bf9-62f46b53896f)

But some of the NGL related pages don't seem to work (https://molstar.org/viewer/).

![image](https://github.com/nglviewer/nglview/assets/7883146/5da04f9c-ed80-49ce-83e2-8da9d446e827)

I'll try an update/reboot. Sometimes with the rolling releases I am on things do get broken.

**Comment by salotz** [comment]
I think its a browser thing. I upgraded and rebooted and I get something but its definitely not working correctly. This is after doing some rotation/translation:

![image](https://github.com/nglviewer/nglview/assets/7883146/22cbf858-c2f7-477c-9903-6b77d3cf4d29)

**Comment by salotz** [comment]
Should have checked before, but looks to be working in Firefox.

**Comment by hainm** [comment]
Weird. I saw similar thing in google colab (playing trajectory and the
structures from multiple frames overlaps.

**Comment by hainm** [comment]
On Thu, Feb 22, 2024 at 10:32 PM salotz ***@***.***> wrote:

> Should have checked before, but looks to be working in Firefox.
>

Oh nice

**Comment by salotz** [comment]
I'll close this. I think its either my browser or something upstream with ngl or other projects.

I checked a bunch of WebGL demos and they all seemed to work in Chrome just fine.
