### ISSUE TITLE
Issue during rendering when using MovieMaker on NGLView

### ISSUE THREAD

**Issue by PieuvreRouge** [nglviewer/nglview#1102]
Hello,

I simply tried to reproduce a film from a page of MDAnalysis website in jupyterlab : "https://userguide.mdanalysis.org/stable/examples/analysis/volumetric/density_analysis.html#Analysing-the-density-of-water-around-the-protein"

```
import MDAnalysis as mda
from MDAnalysis.tests.datafiles import TPR, XTC
from MDAnalysis.analysis import density

import numpy as np
import matplotlib.pyplot as plt
import nglview as nv
%matplotlib inline

u = mda.Universe(TPR, XTC)
view1 = nv.show_mdanalysis(u)
view1.add_representation(
    'licorice',
    selection='resname SOL',
)
view1
from nglview.contrib.movie import MovieMaker
movie = MovieMaker(
    view1,
    step=4,  # keep every 4th step
    render_params={"factor": 3},  # average quality render
    output='density_analysis_images/density_analysis-view1.gif',
)
movie.make()
```

But after trying to do that, I have the following output : 
Rendering ...
without any other indications or error codes.
It sounds like it freezes

Here are the versions of the modules that I use :
numpy                     1.26.4          py312heda63a1_0    conda-forge
nglview                   3.0.8              pyh1da8cd4_0    conda-forge

I don't think my problem is very complicated to solve. I apologise if this problem has already been discussed elsewhere, but I haven't found a satisfactory answer.

Thank you for any help you can provide.

**Comment by hainm** [comment]
Dear @PieuvreRouge 
I think I see this issue before (recently) too. I will investigate (no timeline yet).

**Comment by hainm** [comment]
@PieuvreRouge please `pip install nglview==3.1.2` (latest) and try again. Fixed in #1103.

**Comment by qzchen2022** [comment]
Hi,

I encountered the same problem while try to create movie in jupyter lab, even if I have installed the new version. Here is my code environment:

view=nv.show_mdanalysis(u)
movie = MovieMaker(view, fps=24, output='movie.gif', in_memory=True)
movie.make()

nglview.__version__ : 3.1.2
moviepy.__version__ : 1.0.3
imageio.__version__ : 2.34.0
ffmpeg version 6.1.1 Copyright (c) 2000-2023 the FFmpeg developers

**Comment by hainm** [comment]
Hi

Can you please display the view first and run the movie making in different
cell?

Hai

**Comment by qzchen2022** [comment]
It works, thank you!

**Comment by hainm** [comment]
cheers
