### ISSUE TITLE
nglview 3.1 not working with nbclassic 1.0

### ISSUE THREAD

**Issue by linuxrider** [nglviewer/nglview#1106]
I found that nglview does not work with `nbclassic 1.0`.
It failed to load `ColormakerRegistryModel` from module `nglview-js-widgets` when importing the library. Furthermore, with `nglview.demo()` it could not load `NGLModel`.
With jupyterlab it works without problems, however.
I tested it with Firefox and Chromium with the same result for both. I think a similar issue was reported with vscode #1085.

Here the screenshots for the different environments
`micromamba create -n nglview jupyterlab=4.1.5 nbclassic=1.0 nglview=3.0.8 `
`nbclassic`
![nbclassic 1.0, nglview 3.0.8](https://github.com/nglviewer/nglview/assets/5882359/c8a8d939-a75f-4cee-9335-d729fa5556b4)

`micromamba create -n nglview jupyterlab=4.1.5 nbclassic=1.0 nglview=3.1.2 `
`jupyterlab`
![jupyterlab 4.1.5, nglview 3.1.2](https://github.com/nglviewer/nglview/assets/5882359/ed6d0a0a-7ed3-4682-bdd5-673ad51f8ad1)
`nbclassic`
![nbclassic 1.0, nglview 3.1.2](https://github.com/nglviewer/nglview/assets/5882359/dab50b13-a42d-4c74-bef4-4f95f1d09b96)

**Comment by hainm** [comment]
hi @linuxrider, thanks for your report.

**Comment by hainm** [comment]
Please try latest version, v3.1.4
`pip3 install nglview==3.1.4`
(conda version will be released later via conda-forge)

**Comment by linuxrider** [comment]
Tried it and it seems to work now with nbclassic.
Thanks.
