### ISSUE TITLE
Protein not showing as ribbons

### ISSUE THREAD

**Issue by ONISniperOne** [nglviewer/nglview#1108]
How come nglview isn't showing my protein as ribbons?

# create NGL viewer
view = nv.show_pytraj(traj)
# Change representations
view.add_cartoon(selection="protein")
view

![image](https://github.com/nglviewer/nglview/assets/128614019/cb90a481-f6d0-4dc8-9ef4-5ab9b17f95cd)

1. How do I turn off the atoms for the protein and show only ribbon?
2. How do I change the height of the ipywidget

**Comment by hainm** [comment]
> 1. How do I turn off the atoms for the protein and show only ribbon?

can you try 
```
view.clear()
view.add_cartoon(...)
```

> 2. How do I change the height of the ipywidget

may be `view._set_size(...)` https://github.com/nglviewer/nglview/blob/12a75bc6f0cea8fbc0f75ffc68117d010ce96cc9/nglview/widget.py#L568
