### ISSUE TITLE
A problem when running html result

### ISSUE THREAD

**Issue by lvs0622** [nglviewer/nglview#1115]
![image](https://github.com/user-attachments/assets/2df593af-decb-40e7-ac7f-d62a48ea134a)

The result of my visualization on jupyter notebook is that I can play dynamic motion views, however, when I open the html file with nv.write_html, the image becomes static.
![image](https://github.com/user-attachments/assets/f522053f-35ec-4233-be36-f61837eb6dbb)

(the html file)
![image](https://github.com/user-attachments/assets/d7f168ec-366a-42d7-adaf-cb09ed1c0a0e)
Nothing happens to the image when I press the play button.

**Comment by hainm** [comment]
wow, it turns out user has to explicitly provide `frame_range` args.
nglview doesn't want to write all frames since the data might be big.

```
nv.write_html('index.html', view, frame_range=(0, 4))
```
