### ISSUE TITLE
Black widget on notebook

### ISSUE THREAD

**Issue by lorenzo-rovigatti** [nglviewer/nglview#1120]
Hello,

I'm trying to use nglview in a jupyter notebook but I always get a black widget instead of the structure I want to visualize. Strangely enough, If I use the mouse to rotate or zoom in or out (with the wheel) in the widget, the structure appears, and then disappears as I stop moving the mouse.

Here is a screenshot (taken with Firefox, but I get the same thing with Chromium):

![Screenshot_20240910_093828](https://github.com/user-attachments/assets/f77b50a4-47cd-4e2a-85f8-67f608fa6df8)

and here is a screenshot taken while dragging the widget with the mouse:

![Screenshot_20240910_094029](https://github.com/user-attachments/assets/19d2bec7-5606-43e6-b501-a0f8def9242f)

I'm using the following version:

```bash
python -c 'import nglview; print(nglview.__version__)'
python -c 'import ipywidgets; print(ipywidgets.__version__)'
3.1.2
8.1.5
```

And here is the output of `pip freeze`: [freeze.txt](https://github.com/user-attachments/files/16941204/freeze.txt)

**Comment by hainm** [comment]
This is noted and thanks for your report.

**Comment by hainm** [comment]
@lorenzo-rovigatti Please try again with nglview 3.1.4 if you have a chance. Cheers.

**Comment by lorenzo-rovigatti** [comment]
Sorry for the very late reply. I have updated nglview but the issue persists :(
