### ISSUE TITLE
What do I miss in usage of selections and representations 

### ISSUE THREAD

**Issue by khoroshyy** [nglviewer/nglview#1121]
HI.
I have a protein with two chains.
I want to color them in different color. I use the code below:
####################################
# Load the universe with topology and trajectory
u = mda.Universe('system_nowater.gro', 'selected_frames.xtc')

view2 = nv.show_mdanalysis(u)
view2.clear_representations()

view2.add_representation('cartoon', selection='resid 1-22', color='blue')

# Color atoms 7001-600000 in yellow
view2.add_representation('cartoon', selection='@7123-600000', color='yellow')

# Display the NGLView widget
view2.display()

################

But the whole thing is in blue. 
It may not be necessary, but I run it in a remote Linux session and access it from my Chromebook in VSC. Anyway, I suspect I am missing some logic in the package. Could someone point it out to me?

Thanks.
Petro.

**Comment by hainm** [comment]
hi @khoroshyy I think `nglview` uses `NGL` selection syntax: https://nglviewer.org/ngl/api/manual/selection-language.html

**Comment by khoroshyy** [comment]
My mistake. I was to used to PyMol.
