### ISSUE TITLE
nglview returns just a black empty canvas

### ISSUE THREAD

**Issue by stur86** [nglviewer/nglview#790]
I've just installed the latest nglview in a new conda environment with pip and when I run this basic test code:

```python
import nglview as nv
from ase.build import molecule

v = nv.show_ase(molecule('H2O'))
v.add_ball_and_stick()

v
```
all I get is a wide, black canvas going from side to side of the page with no 3D model, only what looks like the symbol of a minus at the top left. Am I doing something wrong? I did the usual `jupyter-nbextension enable nglview --py --sys-prefix` step, before that I didn't even see the black canvas.

**Comment by hainm** [comment]
I am not sure about your case. It's fine with me.
<img width="1214" alt="Screen Shot 2019-04-26 at 5 40 22 PM" src="https://user-images.githubusercontent.com/4451957/56837974-69003280-684a-11e9-93fc-96bfea615900.png">

can you please post your screen and the javascript dialog (Right click -> Inspect -> console).

**Comment by hainm** [comment]
And does the simple code with ipywdgets work at all?

```
from ipywidgets import Text
Text("hello")
```

**Comment by hainm** [comment]
Since I have not heard from @stur86 so I assume the case is resolved. Feel free to reopen this.

**Comment by stur86** [comment]
Sorry, I didn't have a chance to work on this again during the past week (it only happens on a new computer and I don't have access to it all the time). Here is a screenshot:

![Screenshot from 2019-05-03 12-53-37](https://user-images.githubusercontent.com/4365814/57135829-ac0a5a80-6da2-11e9-98be-758bcfa14e91.png)

And the ipywidget test works just fine.

**Comment by hainm** [comment]
Thanks. can you please post the javascript console (Chrome: Right click -> Inspect -> console)?

**Comment by stur86** [comment]
Here's the console:

    THREE.WebGLRenderer 95 
    ngl.js:1 THREE.WebGLRenderer: EXT_frag_depth extension not supported.
    ngl.js:1 STAGE LOG loading file ''
    ngl.js:1 STAGE LOG loaded ''

There also was another error message that disappeared after I added `%matplotlib notebook` at the top. The canvas is still black though.

**Comment by hainm** [comment]
Hi, can you please separate the issue (use very simple example in a new notebook) and post your screen capture of the js console. This is a new error that I have not seen. 

What’s your browser and its version? 

If this is not too much: can you try ngl directly here (loading some examples to see if you can see the render): http://nglviewer.org/ngl/

**Comment by stur86** [comment]
Ok, I'll do it, but again it'll take a while because I don't use that office until next Thursday. Will get back at you when I have an answer.

**Comment by hainm** [comment]
it seems this issue relates to #799 (happens with Linux + Chrome).
