### ISSUE TITLE
Atom position not updated in PDB Trajectory

### ISSUE THREAD

**Issue by yudongqiu** [nglviewer/nglview#799]
- Description

After loaded a pdb file into a `nglview.Trajectory`, the bonds are updated when playing the trajectory, but the atoms stays in the same initial position.

- code
```
import nglview
import mdtraj
traj = mdtraj.load('scan.pdb')
ngl_traj = nglview.MDTrajTrajectory(traj)
view = nglview.NGLWidget(ngl_traj)
view
```

- Screenshot
![image](https://user-images.githubusercontent.com/6952367/57550483-63f7b480-731b-11e9-90d9-5fa7e7a556eb.png)

- Attachment
[scan.pdb.zip](https://github.com/arose/nglview/files/3167791/scan.pdb.zip)

- OS dependency

This bug happend on Linux with Chrome 73, but did not happen on Mac OS with Chrome 74

- Version report

```bash
>>> python -c 'import nglview; print(nglview.__version__)'
1.2.2

>>>python -c 'import ipywidgets; print(ipywidgets.__version__)'
7.4.2
```

**Comment by hainm** [comment]
thank @yudongqiu  for your detail report. I can not reproduce with my docker image based on "Ubuntu 18.04.1 LTS" and my Chrome 74 (remote notebook via port forwarding on my Mac). What's your linux distro?  `cat /etc/*-release`

By the way, the default background is White, I am not sure how you can get the black with your given code.

**Comment by hainm** [comment]
Also, can you report the output of `view._ngl_version` in your Linux test? It should be `2.0.0-dev.35`

**Comment by hainm** [comment]
<img width="1177" alt="Screen Shot 2019-05-10 at 6 47 17 PM" src="https://user-images.githubusercontent.com/4451957/57560402-367b2d00-7354-11e9-9fdc-dd52e23f76d9.png">

**Comment by yudongqiu** [comment]
@hainm Thanks a lot for the reply! I can confirm that if I use ssh tunnel and open the web page on my Mac Chrome, it works and shows the same white background as your screenshot. 
However, when I open the web page on Linux Chrome, it shows black background and the atom positions are not updating.
My `view._ngl_version` shows `'2.0.0-dev.35'` on my Mac Chrome with ssh tunneling.

**Comment by hainm** [comment]
can you please try with firefox? or upgrade to latest Chrome? thanks.

Also, can you try the NGL web application here: http://nglviewer.org/ngl/
(Examples -> parser/gro-trajectory: then click the player)
<img width="1276" alt="Screen Shot 2019-05-11 at 1 09 23 AM" src="https://user-images.githubusercontent.com/4451957/57565304-6f81c480-7389-11e9-898d-6f44a2018079.png">

**Comment by yudongqiu** [comment]
@hainm I just got back to the workstation running Linux. Here are some of my observations on Ubuntu 16.04:

- Firefox 66.0.3 shows the trajectory correctly.

- After updating to Chrome Version 74.0.3729.131, the trajectory is still not showing correctly, with black background and atom positions fixed. (See screenshot 1)

- The NGL web application has the same problem, when I loaded the pdb file as trajectory. (See screenshot 2)

- Screenshot 1 (Left Firefox, Right Chrome):
![image](https://user-images.githubusercontent.com/6952367/57643974-deb90d80-756f-11e9-8bd6-a95ca9a29ee9.png)

- Screenshot 2 (Left Firefox, Right Chrome):
![image](https://user-images.githubusercontent.com/6952367/57644331-c3023700-7570-11e9-8475-128dc55455f5.png)

**Comment by hainm** [comment]
thanks @yudongqiu  for your effort to debug. It seems that this is an issue with `NGL` itself with `Chrome` on Linux.  I've opened NGL's issue here: https://github.com/arose/ngl/issues/651

**Comment by yudongqiu** [comment]
@hainm Thanks a lot!

**Comment by hainm** [comment]
uhm, my centos 6.8 is not affected (tried with torsiondrive's notebook).

![1](https://user-images.githubusercontent.com/4451957/57649582-a547c880-7596-11e9-9586-81bc74a8c8b5.png)
