### ISSUE TITLE
JS error on mozilla "exceeded 16 live WebGL contexts for this principal, losing the least recently used one"

### ISSUE THREAD

**Issue by ThibaultLacharme** [nglviewer/nglview#889]
Hello,

I got this issue when restarting my kernel several times and getting new cell outputs. For now I have 3 cells outputs where I display molecules from SDF files and when I restart my algorithm a certain amount of times I have all those webGL contexts cumulating, leading to this error (so after restarting the algorithm 6 times).

![Screenshot from 2020-03-31 11-55-48](https://user-images.githubusercontent.com/44061738/78014201-e3cda980-7347-11ea-966c-3a54ba32aa5e.png)

Is there a way to reuse the previous webGL context or killing it when relaunching a cell ?

Perhaps my syntax was incorrect. It's very simple for now, I I just create a NGLWidget with show_structure_file and display it afterwards. 

Are there any options/functions to avoid creating a new WebGL context and this packing up of previously created contexts ?

PS: don't pay attention to the 2 previously closed issues from me, simply forgot that we can't draw new lines in the description (which directly submits the issue instead, very handy)

**Comment by hainm** [comment]
Please close your previous issue(s) if they are duplicated. Thanks.

**Comment by ThibaultLacharme** [comment]
I already closed them, you can delete them if you want as they were made by mistake.

**Comment by hainm** [comment]
May be try this
- Restart/Shutdow the kernel
- Refresh your browser (will clean JS stuff). 
- Run your stuff

**Comment by ThibaultLacharme** [comment]
Restarting the kernel doesn't seem to kill the webGL context, I usually restart the kernel and run all cells.

I actually want to build a GUI which would only run the required cells again depending on what parameters the user modifies, I don't know if refreshing the browser would be possible/viable each time the user wants to get a new result or give new inputs.

Isn't there a way to kill the previous webGL context without refreshing the browser ?

**Comment by ThibaultLacharme** [comment]
Or to reuse the previous webGL context instead if it's possible

**Comment by hainm** [comment]
> Isn't there a way to kill the previous webGL context without refreshing the browser ?

cc @arose

**Comment by hainm** [comment]
>  killing it when relaunching a cell ?

@ThibaultLacharme Can you try `view.close` method? (My random guess)

```
Close method.

Closes the underlying comm.
When the comm is closed, all of the widget views are automatically
removed from the front-end.
```

**Comment by ThibaultLacharme** [comment]
Ok so I tried giving different variable names to each view in order to be able to close them afterwards by simply runnning the last cell.

![Screenshot from 2020-04-01 15-31-59](https://user-images.githubusercontent.com/44061738/78143220-40a38f80-742e-11ea-84d1-97e45b6e5216.png)

By doing so around 5-6 times I unfortunately get the same issue, it the close() method doesn't seem to kill the webGL context.

**Comment by ThibaultLacharme** [comment]
Hello @arose , I don't know if you had time to have a look at it since I raised this issue.

It seems like it would be manageable to erase the webGL context or reuse it but I don't know how it's implemented in NGLview on the webGL side.

**Comment by hainm** [comment]
Too old issue. (not sure if the issue still exists)
