### ISSUE TITLE
Trouble displaying NGLWidget (outputs NGLWidget(max_frame= )

### ISSUE THREAD

**Issue by jacknicoludis** [nglviewer/nglview#891]
I'm having an issue with viewing trajectories. 
```
import mdtraj as mdt
import nglview as nv

m_traj = mdt.load(nv.datafiles.TRR, top=nv.datafiles.PDB)
m_view = nv.show_mdtraj(m_traj)
m_view
```

outputs:

`NGLWidget(max_frame=50)`

This is on a new miniconda-3 installation with python 3.6, jupyter lab 2.0.1, nglview-2.7.5, mdtraj-1.9.3, ipywidgets-7.5.1 (all installed with conda-forge)

I also installed nglview-js-widgets with:

`jupyter labextension install  nglview-js-widgets`

And I've tried:
`jupyter-nbextension enable --py --user widgetsnbextension`
`jupyter-nbextension enable --py --user nglview`

I then tried to upgrade nglview with:
`conda upgrade nglview --force`

This installed nglview-1.1.7 through the bioconda channel (so now I have both 1.1.7 and 2.7.5 in miniconda3/pkgs). Still didn't work. I then tried to remove the 2.7.5 version from my packages and that didn't work (so I put it back). 

Out of desperation I switched to jupyter notebook 😮and it is displaying correctly - so definitely an issue with jupyter lab... but I'd like to figure it out if anyone has suggestions!

**Comment by hainm** [comment]
- Please always use the latest version and remove any python and JS  files from 1.x version
https://github.com/arose/nglview/issues/879

- Do not use `--user` option. The standard install is here: https://github.com/arose/nglview#released-version
Please remove any nglview-related files in user's location. Otherwise, if you upgrade `nglview`, it still uses older files. 

-
> Out of desperation I switched to jupyter notebook 😮and it is displaying correctly - so definitely an issue with jupyter lab... but I'd like to figure it out if anyone has suggestions!

You might need to install `jupyterlab-manager`:
A working script is here: https://github.com/arose/nglview/blob/master/devtools/nglview-jupyterlab.sh
Please adapt it.

**Comment by jacknicoludis** [comment]
Thanks for the quick follow up. I'm confused about which is the latest version: 1.1.7 or 2.7.5. 2.7.5 is obviously a higher number, but 1.1.7 installed when I did upgrade.

How do I find nglview-related files in the user's location? 

After installing jupyterlab-manager, I get the following error when trying to display in jupyter lab:
`Error displaying widget: model not found`

**Comment by hainm** [comment]
Latest means 'higher' (2.7.5 in this ase) I don't know how you configed your conda env. 

> How do I find nglview-related files in the user's location?

https://github.com/arose/nglview/blob/master/docs/FAQ.md#widget-not-shown

> After installing jupyterlab-manager, I get the following error when trying to display in jupyter lab:
> Error displaying widget: model not found

It's tricky to use `nglview` with jupyterlab since it's complicated to build and to debug. That's why we rarely "advertise) this.

This issue might help:
https://github.com/arose/nglview/issues/845

**Comment by jacknicoludis** [comment]
Hi in issue #845, you specifically mention that ngl2.7.0 does not work with jupyter lab (https://github.com/arose/nglview/issues/845#issuecomment-524523545) Is this still true?

So, I went back to https://github.com/arose/nglview/blob/master/devtools/nglview-jupyterlab.sh and made a new environment with the following script and that succeeded in getting nglview to work in jupyter lab (also installing the mdtraj package for loading my trajectories):

**`MD-local.sh`**
```
pythonversion=3.6
nglviewversion=1.1.7
labversion=0.34.12
labmanagerversion=0.37.4
ipywidgetsversion=7.4.2
mdtrajversion=1.9.3
nodejsversion=13.10.1

conda create -n MD-local python=3.6
conda activate MD-local
 
conda install -c conda-forge mdtraj=$mdtrajversion -y
conda install -c conda-forge nodejs=$nodejsversion -y
conda install ipywidgets=$ipywidgetsversion -c conda-forge -y
pip install nglview==$nglviewversion
nglview enable
conda install jupyterlab=$labversion -y -c conda-forge
jupyter-labextension install @jupyter-widgets/jupyterlab-manager@$labmanagerversion
jupyter-labextension install nglview-js-widgets@$nglviewversion
```

(run with `sh MD-local.sh`)

**Comment by hainm** [comment]
uhm, that script is outdated. It should not use v1.17 (https://github.com/arose/nglview/blob/master/docs/FAQ.md#widget-not-shown)

> Hi in issue #845, you specifically mention that ngl2.7.0 does not work with jupyter lab (#845 (comment)) Is this still true?

https://github.com/arose/nglview/issues/845#issuecomment-526654348

**Comment by CareF** [comment]
Same problem. Only text `NGLWidget()` is shown, but not any widgets

**Comment by hainm** [comment]
We have the FAQ here and it helps to resolve the issue most of the time. https://github.com/nglviewer/nglview/blob/master/docs/FAQ.md#widget-not-shown

**Comment by longlongman** [comment]
> Same problem. Only text NGLWidget() is shown, but not any widgets

same here!

**Comment by markerthu** [comment]
> Same problem. Only text `NGLWidget()` is shown, but not any widgets

same here
