### ISSUE TITLE
Trouble displaying system with NGLview

### ISSUE THREAD

**Issue by gnserafim** [nglviewer/nglview#894]
Hi,

I'm current working with a system around 600k atoms and I have trouble visualizing not only the entire sytem but even a small part of it (AtomGroup of 12k atoms).

I followed what was on issue #633 and set NotebookApp.iopub_data_rate_limit as proposed (and even higher) but it didn't work.

Any ideas how to solve this?

As reference, below are the version been used:
jupyterlab 1.2.3
nglview 2.7.5
nglview-js-widgets 2.7.5
jupyterlab-manager 1.1.0

Installation done by pip or jupyter labextensions.

**Comment by hainm** [comment]
>  it didn't work.

Please elaborate.

**Comment by gnserafim** [comment]
Hai,

I set NotebookApp.iopub_data_rate_limit = 10000000 when starting jupyter lab, but nv.show_mdanalysis() doesn't display my system (despite loading the trajectory scroll bar).

![imagem](https://user-images.githubusercontent.com/64193514/80140940-9b00bd80-85a0-11ea-9311-dd0eee788cc0.png)

If I select a small part o the system, I'm able to get an output (first image), but if I my atom group is larger than 10k atoms nglview will not display it (second image).

![imagem](https://user-images.githubusercontent.com/64193514/80140652-29c10a80-85a0-11ea-9ac5-7b85b9b3bdd7.png)

![imagem](https://user-images.githubusercontent.com/64193514/80140838-773d7780-85a0-11ea-91f9-8a3603092ed6.png)

My question is if there is a way to visualize larger systems with nglview and how, or if it has a limit that forbid working large system with this tool

Thanks,

**Comment by hainm** [comment]
Thanks for your detail report. What does the terminal (where you launch the notebook) say?

**Comment by gnserafim** [comment]
Hey Hai,

When I launch the notebook, the below output appears at my terminal:

![imagem](https://user-images.githubusercontent.com/64193514/80195984-98d84680-8614-11ea-9d7a-7c4c09b0803e.png)

I don't know if this is relevantor not, but due to quarentine reasons, I'm accessing my work's computer via ssh from my personal  laptop

**Comment by hainm** [comment]
thanks. I meant **after** you running your code, what does the terminal say? 

Additionally, does it work in traditional notebook?

**Comment by gnserafim** [comment]
> thanks. I meant **after** you running your code, what does the terminal say? 

So, this is the last call of the terminal, even after running the cell of the notebook

> Additionally, does it work in traditional notebook?

Yes. The same thing happens

**Comment by hainm** [comment]
uhm, do you mind sharing your file (pdb) or a toy model so I can play with it?

**Comment by gnserafim** [comment]
Let me know if you need anything else :)

[test.zip](https://github.com/arose/nglview/files/4530550/test.zip)

**Comment by hainm** [comment]
hi @gnserafim 

`nglview` is actually able to show your system but you need to properly center it.
(I guess `nglview` is not robust in this case).

<img width="1130" alt="Screen Shot 2020-04-27 at 2 08 51 PM" src="https://user-images.githubusercontent.com/4451957/80405479-abf74a80-8890-11ea-9ea9-496a65641236.png">

**Comment by gnserafim** [comment]
Hey @hainm 

First, sorry about not replaying you early. Busy week

Thank you for the solution found! I was able to visualize my system centering it the way you did it :)

One more question: your solution only worked in a notebook created through notebook and not through jupyter lab. Any idea why?

**Comment by hainm** [comment]
> One more question: your solution only worked in a notebook created through notebook and not through jupyter lab. Any idea why?

@gnserafim I am not sure why. Does `nglview` work in your lab notebook at all (`nglview.demo()`)
