### ISSUE TITLE
NGL deps updates

### ISSUE THREAD

**Issue by fredludlow** [nglviewer/nglview#902]
Hi,

There have been a few requests to get the upstream NGL code using a more recent version of the three.js library and to make it easier to access globals from the underlying three.js instance.

I've got a [branch](https://github.com/fredludlow/ngl/tree/pr-737) in my NGL fork (based on @garyo's work in arose/ngl#737) which I think does this in a sensible way, but we're obviously very keen to make sure we don't do anything that will break nglview. Essentially it makes three.js a dependency so that downstream projects (like nglview) will install three.js under node_modules and webpack/rollup etc will pull it into your own bundle accordingly.

There's some discussion in this thread: https://github.com/arose/ngl/issues/728

I've just tested building nglview with the following:

1. Clone arose/nglview repository
2. Edit nglview's js/package.json replacing `"ngl": "2.0.0-dev.36"` with `"ngl": "github:fredludlow/ngl#pr-737"`
3. Followed instructions under the jupyterlab section here: https://github.com/arose/nglview/blob/master/CONTRIBUTING.md#jupyterlab-development

This is working locally for me what I've tested (adding a widget via `show_pdbid('1hiv')`). Looking at the nglview code, it imports ngl using es6 modules so I wouldn't expect any problems. What might cause problems is if nglview or anybody's notebooks do something to get direct access to three.js objects.

If anyone can foresee problems, or can check it's working for them that'd be great! You can check out my (minimally modified) version of nglview here: https://github.com/fredludlow/nglview/tree/ngl-pr-737

**Comment by hainm** [comment]
> What might cause problems is if nglview or anybody's notebooks do something to get direct access to three.js objects.

hi @fredludlow, what do you mean in this case?

I don't see any issue with `nglview` to depend on additional package.

**Comment by fredludlow** [comment]
``hi @fredludlow, what do you mean in this case?

I don't know if this is even possible within a notebook but for example directly adding extra things to the three.js scene (and expecting the three.js API to be in a particular place)

I think for the typical use-case (import nglview, do everything through the nglview api) there should be absolutely no difference, it's more asking "is anyone using this in a weird way I don't know about that my changes might break?"

**Comment by hainm** [comment]
just go for it.

**Comment by hainm** [comment]
This can be closed now. thanks @fredludlow.
