### ISSUE TITLE
Simplify jupyterlab installation

### ISSUE THREAD

**Issue by ericpre** [nglviewer/nglview#907]
Currently, to install jupyterlab, it requires to run `jupyter labextension install  nglview-js-widgets`, but it seems that it could that this step could be skipped, see for example, the case of `ipympl`: https://github.com/matplotlib/ipympl#install-the-jupyterlab-extension

**Comment by hainm** [comment]
Nice. Finally. I will have a look.

**Comment by hainm** [comment]
Resolved in 
https://github.com/nglviewer/nglview/pull/967
https://github.com/nglviewer/nglview/pull/955

Thanks @ericpre.
