### ISSUE TITLE
How to add a bond manually ?

### ISSUE THREAD

**Issue by gVallverdu** [nglviewer/nglview#912]
Hi,
I try to visualize a V=O porphyrin and the V=O bond does not appear. I would like to add this bond manually.

Does it exist a function such as add distance but to add a bond ?

```py
view.add_distance(atom_pair=[[23, 49], [4, 49], [54, 49], [73, 49]], label_visible=False)
```

![image](https://user-images.githubusercontent.com/5417018/86400646-49179a80-bca9-11ea-85f2-ff4bfa4cd1e2.png)

Version report

```bash
python -c 'import nglview; print(nglview.__version__)'
2.7.7
python -c 'import ipywidgets; print(ipywidgets.__version__)'
7.5.1
```

**Comment by hainm** [comment]
hi @vhorvath 
> Does it exist a function such as add distance but to add a bond ?

I don't think there is such a function. I think `ngl/nglview` needs to know the topology ahead before rendering. cc @arose. 

You can, however, convert the `.xyz` format to something else e.g: `mol2` that shows the V=0 bond. 

```
view = nv.show_file('your.mol2')
```

**Comment by gVallverdu** [comment]
Hi
I did something using `add_cylinder` but it is not perfect as the cylinder is monocolor (I have to use two half cylinder but ...)

Can you suggest a lib in order to export to mol2 or pdb and define connectivity ?

```py
mol = mg.Molecule.from_file("porVO_chain_SH.xyz")

view = nv.show_pymatgen(mol)
view.shape.add_cylinder(mol.cart_coords[36].tolist(), mol.cart_coords[37].tolist(), [1, 0, 0], 0.2)
view
```

![image](https://user-images.githubusercontent.com/5417018/86493415-c60e4700-bd71-11ea-8972-6229bfb9c937.png)

**Comment by hainm** [comment]
> Can you suggest a lib in order to export to mol2 or pdb and define connectivity ?

Under the hood, `nglview` uses `ASE` to write `.xyz` to `.pdb` format (because `nglview` does not support `.xyz` directly): https://github.com/arose/nglview/blob/e3b1bb0faf32be689ac4901469d9da721fb90863/nglview/show.py#L143

You might want to check `ASE`.
