### ISSUE TITLE
How to change atom color ?

### ISSUE THREAD

**Issue by gVallverdu** [nglviewer/nglview#913]
Hi

I would like to change the default color of one atom (element). I think there might be a kind of parameters of the view where this is defined but I do not found where.

I can add a sphere or something like that as a workaround but this does not change the color of the bond in a ball+stick representation for example.

Thanks

```bash
python -c 'import nglview; print(nglview.__version__)'
2.7.7
python -c 'import ipywidgets; print(ipywidgets.__version__)'
7.5.1
```

**Comment by hainm** [comment]
@gVallverdu may be try to add your own color scheme?

https://github.com/arose/nglview/pull/839

The selection language is here: http://nglviewer.org/ngl/api/manual/usage/selection-language.html

**Comment by gVallverdu** [comment]
Hi
Looking at #839 Yes I can do something. However, I have some difficulties reading the doc here: http://nglviewer.org/ngl/api/globals.html

I am looking for the class from which the `atom` variable is an instance. Can you help me about this point ?

For example I could try something like:

```py
cm.add_scheme_func('my_selection', '''
 this.atomColor = function (atom) {
     if (atom.symbol < "C") {    // HERE I do not know if symbol is an att of atom ???
       return 0x0000FF // color for atom C
     }
 }
''')
```

Thanks

**Comment by hainm** [comment]
@vhorvath Oh, I think we are making thing complicated. See my example below, just use the selection language. 
<img width="1161" alt="Screen Shot 2020-07-05 at 2 31 47 PM" src="https://user-images.githubusercontent.com/4451957/86539662-637d8e00-becc-11ea-847d-c95d6c8395de.png">

**Comment by vhorvath** [comment]
@hainm, I keep getting mentions, but I am not in this thread. Did you mean to add @gVallverdu instead? :)

**Comment by hainm** [comment]
hi @vhorvath  I am terribly sorry. Yes, I meant @gVallverdu

**Comment by gVallverdu** [comment]
@hainm yes this is simpler but the bond are not colored correctly

But for one specific atom or a molecule/fragment not bonded to the whole system it is ok.

![image](https://user-images.githubusercontent.com/5417018/86541531-f2f76100-bf0d-11ea-89af-9b05d372d648.png)

**Comment by hainm** [comment]
@arose any idea? thanks.

**Comment by dominiquesydow** [comment]
Hi @hainm, 

I found this issue while trying to figure out how to recolor all C atoms in an atom selection. 
Do you have any new ideas how the coloring could be extended also to the bonds with non-C atoms?

Minimal code example:
```
view = nglview.show_pdbid("3w32")
view.clear_representations()
view.add_representation("hyperball", selection="ligand")
view.add_representation("hyperball", selection="ligand and _C", color="magenta")
view.center()
view
```

![image](https://user-images.githubusercontent.com/7207093/117582756-d87cae00-b103-11eb-8a70-d877935bfe37.png)

Grey bonds should optimally also be magenta.

---

If this is not easily possible, I might go for the alternative and define element colors using the `ColormakerRegistry` as proposed above:
```
cm = ColormakerRegistry
cm.add_scheme_func('my_sel','''
 this.atomColor = function (atom) {
     if (atom.element == "C") {
       return 0x34495e // C
     } else if (atom.element == "H") {
       return 0xecf0f1
     } else if (atom.element == "S") {
       return 0xf1c40f
     } else if (atom.element == "N") {
       return 0x2980b9
     }
 }
''')
```
Could you maybe link me to the code where the `nglview`-default element colors are defined (for elements other than C, H, S, N, P)? My keyword searches in https://github1s.com/nglviewer/nglview/ where unsuccessful unfortunately, sorry.

**Comment by hainm** [comment]
> Could you maybe link me to the code where the nglview-default element colors are defined (for elements other than C, H, S, N, P)? My keyword searches in https://github1s.com/nglviewer/nglview/ where unsuccessful unfortunately, sorry.

Hi @dominiquesydow: I am sorry that I don't know the answer.
Please search the code in `NGL` repo: https://github.com/nglviewer/ngl

And/or ask the usage of color in that repo since there are many experts there. Good luck.

**Comment by hainm** [comment]
For the color, you can search to JS code here: https://github.com/nglviewer/ngl/tree/master/src/color

**Comment by hainm** [comment]
Thank you all. I go ahead closing this issue. Do feel free to open others if needed.
