### ISSUE TITLE
Get camera real position and pointing direction from view._camera_orientation

### ISSUE THREAD

**Issue by dou-du** [nglviewer/nglview#914]
The view._camera_orientation seems return a 4x4 extrinsic parameter matrix. I try to
get the camera position orientation matrix from the 4x4 matrix according to the 
the instruction: 

https://math.stackexchange.com/questions/82602/how-to-find-camera-position-and-rotation-from-a-4x4-matrix

```python
A = view._camera_orientation
A = np.array(A)

A=A.reshape(4,4)
A=np.transpose(A)

R=A[0:3, 0:3]
T=A[0:3, 3]
Ri = np.transpose(R)
camera_pos = -Ri.dot(T)
camera_ori =  R.transpose().dot(np.array([0, 0, 1]))
```
I try to render it with POYRAY, the camera position and orientation seems wrong. 
I also found the rotation matrix R do not fulfill transpose(R) = inverse(R).

Could you tell me how to obtain the camera real position and orientation (where the camera look at or the direction
vector) ? Thanks.

**Comment by hainm** [comment]
ping @arose.
