### ISSUE TITLE
Bond displayed where there is none

### ISSUE THREAD

**Issue by sneshyba** [nglviewer/nglview#916]
Hi, I just can't seem to solve this problem of a bond being displayed where there is none. In this case, the spurious bond occurs within a dinucleotide, appearing between atom 6 (a C4') and 20 (a nitrogen). 

![image](https://user-images.githubusercontent.com/1376118/88487110-33f3fb80-cf37-11ea-9388-8ea8e25472a3.png)

The bond appears whenever three or more water molecules are included in the .gro. It does not occur when ngl renders the dinucleotide by itself, as in

![image](https://user-images.githubusercontent.com/1376118/88487296-add8b480-cf38-11ea-8626-a28289ff0c55.png)

Attaching the .gro file -- hope you can help me! BTW, I love the combination of MDAnalysis and NGLView -- especially in covid times, when I can get graphics remotely, via jupyter notebook. 

[test_bad.gro.zip](https://github.com/arose/nglview/files/4978219/test_bad.gro.zip)

**Comment by hainm** [comment]
hi @sneshyba, you might need to `clear` to remove the default representations. 

```
u = mda.Universe('./test_bad.gro')
view = nv.show_mdanalysis(u)
view.clear()
view.add_ball_and_stick()
view
```

**Comment by sneshyba** [comment]
That did it! Thank you!
