### ISSUE TITLE
visualization for multiple pdb file

### ISSUE THREAD

**Issue by spydr1** [nglviewer/nglview#918]
- Version report 
nglview '2.7.7'

hi 
I want to visualize like this. 
if i have multiple pdb files. and it is represented each time step. 

ex) 
T1080_1.pdb
T1080_2.pdb
... 

can i visualize using the your code ? 

https://miro.medium.com/max/1050/1*9ocTy0r7fijGYm_TGoq58g.gif 

thanks a lot !

**Comment by hainm** [comment]
hi @spydr1, 
you can use [pytraj](http://amber-md.github.io/pytraj/latest/installation.html) (Linux or MacOS only) (or may be mdtraj, mdanalysis) to read multiple pdb into a single trajectory and visualize it.

```python
import nglview as nv
import pytraj as pt

traj = pt.load(['your_1.pdb', 'your_2.pdb', ...], top='your_1.pdb')
view = nv.show_pytraj(traj)
view
```

**Comment by spydr1** [comment]
@hainm 
thanks a lot !! 
It is very helpful my work.
