### ISSUE TITLE
Draw a box from atoms coordinates

### ISSUE THREAD

**Issue by gbayarri** [nglviewer/nglview#919]
Hi, I have 8 atoms coordinates that conform a box. Is there any way to connect these atoms to draw a box or to draw a box wit their coordinates?

I don't understand why there is no box item in the shape class, so probably I'm missing something in the documentation ;)

Here you have a screenshot with the atoms over the structure:

![screenshot](https://user-images.githubusercontent.com/19928100/88915584-dfb58800-d264-11ea-8ab8-f025763b2491.png)

**Comment by hainm** [comment]
hi @gbayarri, may be try `add_cylinder `? 
https://github.com/nglviewer/nglview/blob/2cd42979e0c39c163b6728f59ffea6e9d8cd56db/nglview/shape.py#L25

**Comment by gbayarri** [comment]
Hi @hainm, I can't see the way to convert a cylinder in a box. Is there any border radius parameter?

**Comment by hainm** [comment]
you can use that `to connect these atoms to draw a box`

**Comment by gbayarri** [comment]
Ok, got it.

Thanks!
