### ISSUE TITLE
How to display hydrogen bonds

### ISSUE THREAD

**Issue by sneshyba** [nglviewer/nglview#920]
I'm sorry, this isn't an "issue" but a matter of me not being able to figure something out: I’m trying to display hydrogen bonds between two groups — solvent water and specified atoms of a solute (produced by an MD run in gromacs). Can you point me to how to do that? Thank you!

**Comment by hainm** [comment]
hi @sneshyba 

may be try

```
view. add_contact(hydrogen_bond=True)
```

PS: I recall the `add_contact` method from the issue you've posted: https://github.com/nglviewer/ngl/issues/546)

**Comment by hainm** [comment]
I go ahead closing this case since I have not heard the feedback. Feel free to reopen it.

**Comment by sneshyba** [comment]
I am so sorry, Hai — I think I must have messed up in posting the response. That solution worked!

On Sep 23, 2020, at 1:51 PM, Hai Nguyen <notifications@github.com<mailto:notifications@github.com>> wrote:



I go ahead closing this case since I have not heard the feedback. Feel free to reopen it.
