### ISSUE TITLE
show_mdtraj does not return image

### ISSUE THREAD

**Issue by fabiooliveira-at-uib** [nglviewer/nglview#921]
I am still experiencing the problem on Jupyter Notebook. When using nglview.show_mdtraj I don't get any image.
Here: 
![Screenshot from 2020-08-04 11-10-50](https://user-images.githubusercontent.com/67099904/89276182-9f2e8380-d643-11ea-9270-2aa5797235a8.png)

How do I solve it? Thank you!
List of all packages and versions: [py37_deepchem.txt](https://github.com/nglviewer/nglview/files/5021157/py37_deepchem.txt)
And my Ubuntu version is 18.04.4

_Originally posted by @fabiooliveira-at-uib in https://github.com/nglviewer/nglview/issues/726#issuecomment-668483428_

**Comment by hainm** [comment]
Please see the solution here: https://github.com/nglviewer/nglview/blob/master/docs/FAQ.md#widget-not-shown

**Comment by fabiooliveira-at-uib** [comment]
Thank you for redirecting me to that resource. It is working properly now :)
