### ISSUE TITLE
Link to NGLview from the pyiron website

### ISSUE THREAD

**Issue by jan-janssen** [nglviewer/nglview#922]
Inside the pyiron project https://github.com/pyiron we use NGLview to visualise atomistic structures and we are very happy that you link to our project in the README.md file. Now we want to return the favour and link NGLview on the updated pyiron website: https://pyiron.org/collaborators/ 

Is there any logo we can use for this kind of backlink?

**Comment by hainm** [comment]
hi @jan-janssen, there is no logo for `nglview` yet. And I think the icon in pyiron's website looks pretty. Cheers.
