### ISSUE TITLE
How to add custom label?

### ISSUE THREAD

**Issue by diallobakary4** [nglviewer/nglview#923]
I am trying to add a custom label to a ligand without success. 
Here is what I have tried so far.

```
view.add_label("488", labelType="resname", labelGrouping = 'residue')#, color ="black") 
```
The above does work but it's not custom.
None of the below does work for custom label!
```
view.add_label("488", labelText=["ZINC000050633276"], labelType="text")
view.add_label("488", labelText="ZINC000050633276", labelType="text")
view[0].add_representation('label', selection= "488", name= 'myLabel', labelType= 'text', labelText= ["ZINC000050633276"])
```
I am not sure what is the right syntax.
I am reading from a trajectory, so quite difficult to share.

nglview 2.7.7
ipywidgets; 7.5.1

**Comment by hainm** [comment]
hi @diallobakary4, please try `view.shape.add_label`
https://github.com/nglviewer/nglview/pull/663

**Comment by juliasubbotina** [comment]
@diallobakary4 
Something like this should work:
```
    view.add_representation(repr_type="label", name = "label", showBackground = True, labelType = "atomname", color = "black", 
                     sele = bSel,   xOffset = 0.5 , zOffset =5 )
```

Full description of options can be found [here](https://nglviewer.org/ngldev/api/file/src/representation/label-representation.js.html).
The result will look like this:


 
![eq_ua_chl1_cgMap_0](https://user-images.githubusercontent.com/82937099/201330094-eb5d5ee2-9854-40ae-a3e9-c52f912955e0.png)

**Comment by hainm** [comment]
Thanks @juliasubbotina

**Comment by juliasubbotina** [comment]
@hainm @arose 
Apparently as @diallobakary4 has mentioned, the labelType="text" is not working. I have the same issue ([#1047](https://github.com/nglviewer/ngl/issues/1047)) Changing atom names is a workaround, but not always safe/useful.  
Maybe somebody can take a deeper look into it.
