### ISSUE TITLE
Can nglview be used to image XYZ format?

### ISSUE THREAD

**Issue by scottwsides** [nglviewer/nglview#927]
Now that py3Dmol isn't working with new Jupyterlab... I wanted to use nglview to make interactive 3D images of molecules using XYZ embedded in Jupyterlab notebook. I assume this is possible... but I can't find it. 

(Sorry the usage link didn't work. )

**Comment by hainm** [comment]
Hi, you can use ase to read your xyz file and use nglview.show_ase(...)

**Comment by scottwsides** [comment]
Thanks hainm! Just to be sure, if I input an xyz file for a nearly optimized structure for say.... thiophene... then all the correct bonds will be drawn?

**Comment by hainm** [comment]
I don’t know for sure. Please try nglview yourself in jupyter notebook first. Cheers.

**Comment by scottwsides** [comment]
Sorry to be slow... but the docs don't really give a concrete example. If my data is in 'thiophene.xyz' .... what are the calls to visualize?

**Comment by hainm** [comment]
You can use `ase` package to read your `.xyz` file.
```
from ase import io
mol = io.read('thiophene.xyz')
view = nglview.show_ase(mol)
view
```

**Comment by scottwsides** [comment]
Thanks hainm! Actually, the openbabel example worked too. But my stack already has ase so I think I'll use that.

**Comment by scottwsides** [comment]
Just to push my luck... is there a way that nglview can change the color of the atoms shown?

**Comment by hainm** [comment]
Please try the document first: https://github.com/nglviewer/nglview#representations

**Comment by scottwsides** [comment]
I did see that.... but I want is to change the color of say 'C' (carbons) in my xyz file to 'cyan'. I don't see it in the 'Representations' discussion. Also, how to change atoms scaling size compared to bonds. And I guess while I'm at ... can I turn off the drawing of bonds?

**Comment by hainm** [comment]
>  but I want is to change the color of say 'C' (carbons) in my xyz file to 'cyan'.

@scottwsides  You can use selection for atom here: http://nglviewer.org/ngl/api/manual/selection-language.html

> Also, how to change atoms scaling size compared to bonds.
You can play around with different parameters here: http://nglviewer.org/ngl/api/manual/molecular-representations.html
I suggest to play with `NGL`'s webapp first: http://nglviewer.org/ngl/
(Under the hood, `nglview` is using `NGL`).

> And I guess while I'm at ... can I turn off the drawing of bonds?

I am not so sure. Please experiment yourself or ask `NGL`'s developer here: https://github.com/nglviewer/ngl/issues

**Comment by scottwsides** [comment]
Thanks!

**Comment by fredludlow** [comment]
Not sure how it maps to nglview but in NGL the representation params would
be colorScheme: "element", colorValue: "cyan"

**Comment by hainm** [comment]
@fredludlow: it can be mapped to `nglview` by following:
```
view.add_line(colorScheme='element', colorValue='cyan', ...) # or using camel color_scheme='element'
```
Thanks.
