### ISSUE TITLE
Support JLab 3

### ISSUE THREAD

**Issue by hadim** [nglviewer/nglview#932]
Is there is a plan to test the extension against the soon to be coming jlab3?

See also:

- https://www.quansight.com/post/why-we-are-excited-about-jupyterlab-3-0-dynamic-extensions
- https://github.com/jupyterlab/jupyterlab/issues/8038

**Comment by hainm** [comment]
hi @hadim: there is no plan yet (because I do not keep track the new feature in jupyterlab). But I guess users will report issues anyway.

**Comment by jaimergp** [comment]
The new `nodejs`-less packaging sounds kind of exciting! https://jupyterlab.readthedocs.io/en/latest/getting_started/changelog.html#extensions-can-be-installed-without-building-jupyterlab-with-nodejs

Is this going to be supported?

**Comment by hainm** [comment]
Thanks all. To accelerate the process, PR is always welcome.

**Comment by hadim** [comment]
Migration guide: https://jupyterlab.readthedocs.io/en/latest/extension/extension_migration.html
Cookiecutter extension: https://github.com/jupyterlab/extension-cookiecutter-ts

**Comment by muh-hassani** [comment]
any updates in this regard?

**Comment by hainm** [comment]
I am sorry, I don't have available time to work on this yet.

**Comment by jaimergp** [comment]
I want to tackle this at some point before winter is over but I have some more stuff on my list first!

**Comment by scottwsides** [comment]
I"ll just pile on and say that nglview upgrading to the 'nodejs-less' setup with JupyterLab 3 would be awesome!!!

**Comment by robertodr** [comment]
#955 should have fixed this.
