### ISSUE TITLE
repr_type api link not found

### ISSUE THREAD

**Issue by davidcwang** [nglviewer/nglview#934]
The link to more info on the `repr_type` variable seems like it's down or doesn't exist anymore.

http://arose.github.io/ngl/api/

**Ref**: http://nglviewer.org/nglview/dev/api.html#nglview.NGLWidget.add_representation

**Comment by hainm** [comment]
thanks @davidcwang for pointing out. Please replace `arose.github.io` by `nglviewer.org`
The link should be http://nglviewer.org/ngl/api/

**Comment by hainm** [comment]
I've opened a new issue in NGL: https://github.com/nglviewer/ngl/issues/815

**Comment by davidcwang** [comment]
Opened a PR for nglview https://github.com/nglviewer/nglview/pull/935

**Comment by davidcwang** [comment]
Resolved https://github.com/nglviewer/nglview/pull/935
