### ISSUE TITLE
nglview double bonds representations

### ISSUE THREAD

**Issue by sntgluca** [nglviewer/nglview#936]
Hi!

I have been searching both on google and in the documentation without success.

Is it possible to show double bonds in the licorice / ball&stick representations, in a similar way as it's done in Pymol with the `valence` parameters (https://pymolwiki.org/index.php/Valence)?

Thanks for any answer!

**Comment by hainm** [comment]
@sntgluca  please try `multipleBond='symmetric` option:

<img width="1344" alt="Screen Shot 2020-12-03 at 11 48 35 AM" src="https://user-images.githubusercontent.com/4451957/101060565-8be1e500-355d-11eb-82a5-61b7401bb043.png">

**Comment by sntgluca** [comment]
@hainm this is exactly what I was looking for :) Many many thanks also for your speed!

Since we're on the topic, I am _obviously_ not familiar with NGLViewer, and I am using the python API via the JupyterLab plugin. Where do I find the detailed documentation? I searched for hours without success...

**Comment by hainm** [comment]
You have too look at NGL website: http://nglviewer.org/ngl/api/manual/index.html

The best way is to play with its webapp to see the options in action: http://nglviewer.org/ngl/

cheers

**Comment by sntgluca** [comment]
This is marvellous, thanks.

**Comment by hainm** [comment]
@sntgluca  one more point: you can specify `view.gui_style = 'ngl'` to bring the whole webapp to the notebook.
https://github.com/nglviewer/nglview/pull/830
