### ISSUE TITLE
Help: Colouring

### ISSUE THREAD

**Issue by DustBytes** [nglviewer/nglview#937]
Hi,

I need to put colors on each chain, which can be done with colorScheme: "chainid"   but I also need to put custom colors on certain residues, which is possible via color: My_schemeId.
Imagine it like 4 chains colored via colorScheme and 10 residues from each chain are in let's say orange color. 
If I put both, only "color" is active and  colorScheme is ignored. In My_schemeId, the " * " coloring is not added but still no effect. I tried changing order but still color is active.

Writing custom colors for each chain is not a practical solution as chain number varies.
How can we do both?

Thank You

**Comment by hainm** [comment]
> I tried changing order but still color is active.

Can you make a code example that can be reproduced?

**Comment by DustBytes** [comment]
I made this small example:

https://jsfiddle.net/ku1fhgrn/1/


Thank You

**Comment by hainm** [comment]
Thanks @DustBytes. I see the issue now. Let me think about it. 
Mean while, you can ask `NGL` developers directly since they know best about it: https://github.com/nglviewer/ngl/issues

**Comment by DustBytes** [comment]
Any ideas please?

**Comment by hainm** [comment]
hi @DustBytes  I don't have any clue yet. For `NGL` questions, it would be better to ask NGL's developers. https://github.com/nglviewer/ngl/issues
