### ISSUE TITLE
Balls&sticks representation: wrong bonds when atom moves across unit cell boundaries

### ISSUE THREAD

**Issue by freude** [nglviewer/nglview#938]
When using the balls and stick model and performing the geometry relaxation of a periodic structure, I observe a weird behavior for the ball and stick representation. When an atom moves across the boundary of the unit cell it appears from the other side as it should be, but the stick representing a bond is not recalibrated becoming very long stretching from one side of the unit cell to the other. Is there a way I can improve the ball and stick representation in this context? It seems like the list of bonds has not been updating since the first frame in the trajectory.

Below is the representations I am using:

v.view.representations = [
    { "type": "unitcell", "params": {
        "sele": "all", "color": "residueindex"
    } },
    { "type": "ball+stick", "params": {
        "sele": "all"
    } }
]

**Comment by hainm** [comment]
> It seems like the list of bonds has not been updating since the first frame in the trajectory.

That's true.

> Is there a way I can improve the ball and stick representation in this context?

I guess you need to reimage your system (e.g: https://amberhub.chpc.utah.edu/autoimage/)

**Comment by freude** [comment]
The link refers to the AMBER site and its APIs. Does it mean that this problem cannot be solved by the means of the nglviewer tools?

**Comment by freude** [comment]
The representation "hyperball" does the job. The issue can be closed.
