### ISSUE TITLE
Need help - set_coordinates does not seem to work for components.

### ISSUE THREAD

**Issue by vaddanki69** [nglviewer/nglview#940]
nglview.__version__=2.7.7
ipywidgets.__version__=7.6.2

I was able to successfully add and display 2 proteins as 2 components in a single view. However, they are overlapping each other and set_coordinates does not seem to work. Please help.

------- code start --------
from nglview import NGLWidget

viewWidget = nglview.NGLWidget()

c1 = viewWidget.add_pdbid("7d4f")
c1.set_coordinates(np.array([0, 0, 0]))
c1.add_representation('surface', color='chainindex')

#viewWidget.add_representation('surface', color='chainindex')

c2 = viewWidget.add_pdbid("6yyt")
c2.set_coordinates(np.array([80, 80, 80]))
c2.add_representation('surface', color='chainindex')

#c3 = viewWidget.add_pdbid("6xez")
#c3.set_position([80, 80, 80])

viewWidget

------- code end --------

- Question about usage? Please search your issue here first: https://github.com/arose/nglview/issues/589 and https://github.com/arose/nglview/issues/785

- Version report

```bash
python -c 'import nglview; print(nglview.__version__)'
python -c 'import ipywidgets; print(ipywidgets.__version__)'
```

**Comment by hainm** [comment]
hi @vaddanki69, use `set_position` instead.

```
c1.set_position([0, 0, 0])
c2.set_position([80, 80, 80])
```

`set_coordinates` is used for setting 3D coordinates of the system for corresponding frame (mainly for trajectory).

**Comment by hainm** [comment]
Close this case since I don't hear the feedback. Feel free to reopen if you still have any Q. Cheers.
