### ISSUE TITLE
add_annotation equivalent

### ISSUE THREAD

**Issue by gbayarri** [nglviewer/nglview#943]
Hi, is there any way to perform annotations in nglview? Exactly like the **interactive/annotation** example in the nglviewer gallery example:

http://nglviewer.org/ngl/gallery/

nglview 2.7.5
ipywidgets 7.5.1

Thanks!

**Comment by hainm** [comment]
hi @gbayarri 

You can use `view._execute_js_code` to call the NGL directly.
Use this.stage for `stage` in your example

https://github.com/nglviewer/nglview/pull/768

**Comment by hainm** [comment]
Or just use `add_label`

https://github.com/nglviewer/nglview/pull/627

**Comment by gbayarri** [comment]
Hi @hainm, thanks for answering so fast

> hi @gbayarri
> 
> You can use `view._execute_js_code` to call the NGL directly.
> Use this.stage for `stage` in your example
> 
> #768

That's perfect, it did the trick for me. Thank you.

> Or just use `add_label`
> 
> #627

Well, I've tried before opening this issue, but I'm not able to get the coordinates of a nglview.component.ComponentViewer to locate the label properly. I'm sure it shouldn't be difficult, but I didn't get through.

**Comment by gbayarri** [comment]
Just a question, how can I inject pyhon code inside the JS code? Something like:

```
var whatever = 'something'
code = """
var stage = this.stage;
var view = this.stage.viewer;
for (x in view){
    console.log(x)
}
console.log(this.whatever) // print value of whatever python variable
"""
v._execute_js_code(code)
```

**Comment by hainm** [comment]
The `code` is just string, you can do whatever with the string, e.g: use string format in python to insert the value.

whatever = 'something'
code = "%s" % whatever

**Comment by gbayarri** [comment]
ok, thanks
