### ISSUE TITLE
NGLview prints 'NGLWidget()' instead of the image

### ISSUE THREAD

**Issue by phisanti** [nglviewer/nglview#944]
Hi, I am trying to see a simple PDB, but for some reason, the plot doesn't come out. It only prints the name of the function. Here is the code:

```python
from __future__ import print_function

import pytraj as pt
import nglview as nv

traj = pt.load('wt1mg.pdb')
view = nv.show_pytraj(traj)
view

output:

NGLWidget()

 ```
Surprisingly, the output is just a text with the name of the function. I have tried to look for similar issues but couldn't find so decided to write made this report.

The code is just an example taken from https://ambermd.org/tutorials/analysis/tutorial_notebooks/nglview_notebook/index.html

Heres is the version of the software I using.

```bash
$ python -c 'import ipywidgets; print(ipywidgets.__version__)'
7.6.3
$ python -c 'import nglview; print(nglview.__version__)'
2.7.7
 ```

**Comment by hainm** [comment]
hi @phisanti 

Have you followed the steps in here yet? https://github.com/nglviewer/nglview#released-version
(e.g: `jupyter-nbextension enable nglview --py --sys-prefix`)

Related issues: https://github.com/nglviewer/nglview/issues?q=jupyter-nbextension+enable+nglview+--py+--sys-prefix

Cheers

**Comment by hainm** [comment]
I don't see the feedback so I assume the issue is resolved.

**Comment by PicciF** [comment]
i have this problem in vs code, any solution?

**Comment by hainm** [comment]
> i have this problem in vs code, any solution?

Unfortunately I know nothing about this. Sorry.
