### ISSUE TITLE
Getting Nglview going in Kaggle platform

### ISSUE THREAD

**Issue by phu004** [nglviewer/nglview#947]
I am trying to get nglview going using Kaggle platform.

This is my installation code:
**python -m pip install git+https://github.com/arose/nglview
jupyter nbextension enable --py widgetsnbextension**

However when I try to run ngview, i.e.
**import nglview
view = nglview.show_pdbid("3pqr")
view**

It only output the message "NGLWidget()" without showing any window or error.

Can anyone suggest what I might be doing wrong?

**nglview: 2.7.7
ipywidgets: 7.6.2**

browser console error track: 

**manager-base.js:273 Could not instantiate widget
utils.js:119 Error: Could not create a model.
    at utils.js:119**

Thanks in Advance!

Pan

**Comment by hainm** [comment]
Try to enable `nglview` too: `jupyter-nbextension enable nglview --py --sys-prefix`

**Comment by phu004** [comment]
I have tried that as well, unfortunately I am still getting the same error.

**Comment by hainm** [comment]
@phu004 Can you make the `ipywdgets` work?

```
import ipywidgets as Text
Text("HELLO")
```

If that does not work, I don't think your platform support it. 
Similar issue: https://github.com/nglviewer/nglview/issues/816

**Comment by phu004** [comment]
Thanks for replying, I got the following from executing Text("HELLO")
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-4-a86e427e1b83> in <module>
      1 import ipywidgets as Text
----> 2 Text("HELLO")

TypeError: 'module' object is not callable

However executing Text.IntSlider() works

**Comment by hainm** [comment]
> import ipywidgets as Text

My bad. `import ipywidets; ipywidgets.Text("hello")`

> However executing Text.IntSlider() works

Did you kill/close your notebook and reopen the session after enabling `nglview`?

**Comment by phu004** [comment]
In kaggle, if you close the notebook session, any change you have made to the kernel (such as installed packages) are lost.

So what I did is starting a fresh notebook instance and re-do all the steps plus the "enable" line. But it doesn't seem to make any difference.

**Comment by hainm** [comment]
Then I am sorry not able to help. I am not familiar with the platform.
