### ISSUE TITLE
Help: change molecular structure displayed by a specific NGLWidget object

### ISSUE THREAD

**Issue by enricogandini** [nglviewer/nglview#949]
Is it possible to change the molecular structure displayed by a specific NGLWidget object?

I am trying to build a sort of quiz app, using [asynchronous widgets](https://ipywidgets.readthedocs.io/en/latest/examples/Widget%20Asynchronous.html). I have a list of molecules. I want to show each molecule to the user and ask him a question. When the user has answered, I want to display the next molecule and ask him the next question.

I have already built the basic asynchronous architecture to create this sort of interactive quiz. I only need a way to change the structure that is represented by an NGLWidget object.
Is there a recommended way to do this? If it is not possible to do exactly what I asked, I would still appreciate suggestions!

**Version report**
Python 3.7.9
ipywidgets 7.6.3
nglview 2.7.7
Jupyter Lab 3.0.5
Environment installed with Anaconda

**Comment by hainm** [comment]
hi @enricogandini: You can try `show_only`: https://github.com/nglviewer/nglview/blob/master/nglview/widget.py#L1464
`view.show_only([2])`  # only show the 3rd structure.

Let me know if that helps.

**Comment by enricogandini** [comment]
Thank you for your answer @hainm!

The code does not work for me, and I do not know if there is something wrong with my file, or if NGLWidget is not supposed to load my file.

I am not dealing with multiple conformers of a single molecule (i.e., a trajectory). I am dealing with multiple molecules, with different topologies.
Please find attached an example file:  [two_molecules.mol2.txt](https://github.com/nglviewer/nglview/files/5988167/two_molecules.mol2.txt), which contains two different molecules (each molecule with a single conformer).

I created an NGLWidget with helper function `view = nv.show_structure_file("two_molecules.mol2")`.
I get a view with the first molecule. If I then use `view.show_only[1]`, I get a white screen with no molecule. So, I am assuming that `show_structure_file` function only parsed the first molecule in the file, am I right?
I am pretty sure that the file is correctly formatted, since Jmol is able to open it as a "collection of 2 models".

I do not even know if it is possible to obtain an NGLWidget with multiple molecules. How could I do that?

On the other hand, my preference would be to have separate single-molecule files (or separate RDKit Mol objects), and switch the molecule displayed by an NGLWidget. Would this be possible?
