### ISSUE TITLE
molecule not displayed in Voilà, is displayed if window size changed

### ISSUE THREAD

**Issue by enricogandini** [nglviewer/nglview#950]
I am building a [Voilà](https://github.com/voila-dashboards/voila) app, where ipywidgets and an NGLWidget are changed in an asynchronous for loop.
My NGLWidget is in a VBox, it displays a molecule, and when the user clicks a button, a new molecule is displayed.
Everything works perfectly inside Jupyter Lab.

When using Voilà, I encounter a minor but annoying inconvenience.
The NGLWidget window is white at first, with no molecule displayed:
![empty_view](https://user-images.githubusercontent.com/52758483/108231714-54d5a580-7142-11eb-8170-749656c0a13d.png)

When I click and move the "change window size" button in the bottom right corner of the window (circled in red in the above picture), the molecule appears:
![molecule_view](https://user-images.githubusercontent.com/52758483/108232243-da595580-7142-11eb-83f0-3da8adf39339.png)

When I click the button to switch to the next molecule in the loop, the molecule is displayed correctly from the start, no need to click and move the "change window size" button.

I understand that this "issue" is very complex, since it depends on Voilà.
But is there any programmatic way to "refresh" the window, to somehow "replicate" the "change window size" event that is triggered by the mouse?
I just want the molecules to appear right at the start of the Voilà app, with no need for the user to change the window size.
I would also appreciate suggestions on other ways to achieve the same result.

I have already tried `center` and `update_representation` methods of NGLWidget, and I tried to change `camera` from "orthographic" to "perspective", but the problem persists.
I also tried to wrap the NGLWidget inside a Box, and to set fixed width and height, with no avail.

**Version report**
Python 3.7.9
ipywidgets 7.6.3
nglview 2.7.7
Jupyter Lab 3.0.5
Environment installed with Anaconda

**Comment by hainm** [comment]
@enricogandini You can try GridspecLayout or AppLayout instead of Vbox. I see the issue before.

**Comment by hainm** [comment]
Please see this thread, it might give you some hints: https://github.com/nglviewer/nglview/issues/873

**Comment by enricogandini** [comment]
Thanks @hainm, you are my saviour!
`GridBox` did not solve my problem, but `handle_resize` method that you recommended in #873 did!
I just have to use `handle_resize` in my asynchronous for loop, after a molecule is added to an `NGLWidget`.
Also thanks for pointing me to #873, it will be useful since the next step of my project involves displaying two `NGLWidget` objects next to each other.

**Comment by enricogandini** [comment]
@danielhollas I'm happy to help if I can!
The whole code I used is published in this [notebook](https://github.com/enricogandini/paper_similarity_prediction/blob/main/webapp/survey_molecular_similarity/survey.ipynb) in a public repository of mine.
