### ISSUE TITLE
Reset initial display

### ISSUE THREAD

**Issue by enricogandini** [nglviewer/nglview#951]
Is it possible to reset the initial view of a `NGLWidget`?
I mean something like pressing `=` in VMD: a way to reset initial zoom, camera orientation, molecule position.

`view.center()` only puts the molecule in the center, but does not reset the zoom or the camera orientation.

In order to reset initial camera orientation, I tried to get the initial orientation (when molecule is initially displayed) with `initial_orient = view._camera_orientation`, and then to reset to initial orientation with `view.control.orient(initial_orient)`.
But this does not reset zoom or center the molecule.

How can I reset the zoom?
Is there a single command to reset everything to the initial display?

**Comment by hainm** [comment]
@enricogandini can you try this method? https://github.com/nglviewer/nglview/blob/2cd42979e0c39c163b6728f59ffea6e9d8cd56db/nglview/widget.py#L347

**Comment by enricogandini** [comment]
Thanks @hainm!
It works! After `view` is displayed, I save the initial orientation: `init_orient = view._camera_orientation`.
Then the molecule can be moved in any way: rotated, translated, zoomed...
Then, using `view._set_camera_orientation(init_orient)` brings back the initial display, just as `=` command would do in VMD.

It is important that `init_orient` is saved after the `view` is displayed: otherwise, `_camera_orientation` would be an empty list, and `_set_camera_orientation([])` doesn't do anything!

If I may suggest a minor improvement: add an attribute `_initial_camera_orientation` to displayed `NGLWidget` objects, and a method `reset_camera_orientation` that basically does `_set_camera_orientation(self._initial_camera_orientation)`.

**Comment by hainm** [comment]
Thanks for your suggestion. It's tricky to do it properly so we hide the methods for now.

**Comment by enricogandini** [comment]
Ok! Is there any explanation on `_camera_orientation`? It is a list of 16 numbers, what are those numbers about?

**Comment by hainm** [comment]
I guess it's the 4x4 rotation matrix.
