### ISSUE TITLE
nglview-js-widgets folder not created after installation

### ISSUE THREAD

**Issue by BSharmi** [nglviewer/nglview#952]
- Question about usage? Please search your issue here first: https://github.com/arose/nglview/issues/589 and https://github.com/arose/nglview/issues/785

- Version report

```bash
python -c 'import nglview; print(nglview.__version__)'
2.7.7
python -c 'import ipywidgets; print(ipywidgets.__version__)'
7.6.3
```
Hello,
I am using python 3.8 and followed https://github.com/Amber-MD/pytraj/issues/1508#issuecomment-676856044 to get pytraj via ambertools but get import error when I import pytraj
```
import pytraj as pt
```

I also installed nglview-js-widgets by the command below
```
jupyter labextension install  nglview-js-widgets
```
but I do not see the nglview-js-widgets folder under ~/anaconda3/share/jupyter/nbextensions (there is a jupyter-js-widgets but I do not think this is the same).

The simple demo below does not output anything 
```
import time
import nglview as nv

view = nv.demo()
view
```
but I see a Hello box with the Text demo.

I went through the debug user stories and reinstalled nglview cannot figure out what is missing. 

Would really appreciate help!
Thank you!

**Comment by hainm** [comment]
hi @BSharmi, try `nglview` with the traditional notebook first. `nglview` might not work with the latest lab version.

By the way, this script is known to work: https://github.com/nglviewer/nglview/blob/master/devtools/nglview-jupyterlab.sh

**Comment by BSharmi** [comment]
Thanks so much for the response!
I used the shell script to create a new env and do the rest of the installation. Could you please point me to the traditional notebook?

**Comment by hainm** [comment]
> Could you please let me know what did you mean by traditional notebook? Is there a link somewhere?

`jupyter-notebook` --> traditional notebook
`jupyterlab` --> lab notebook

**Comment by BSharmi** [comment]
I checked that I was using notebook and not lab, so not sure why the error is. I will search online for similar issues from other users until I can figure out the problem

Thank you!

**Comment by hainm** [comment]
@BSharmi  Have you run `jupyter-nbextension enable nglview --py --sys-prefix` to enable the nglview JS extension yet?

https://github.com/nglviewer/nglview#released-version

**Comment by hainm** [comment]
https://github.com/nglviewer/nglview/blob/master/docs/FAQ.md#widget-not-shown

**Comment by BSharmi** [comment]
Yes I did
```
jupyter-nbextension enable nglview --py --sys-prefix
```
deleted nglwidgets folder, uninstalled and reinstalled nglview and upywidgets as suggested in the debug issues. I still don't see widgets

**Comment by hainm** [comment]
I am sorry to hear that.
It would be better to create a fresh conda env and redo your work:

```
conda create -n your_env python=3.8
source activate your_env
conda install -c conda-forge nglview
jupyter-nbextension enable nglview --py --sys-prefix
```

and then try below again: 
```
import nglview as nv

view = nv.demo()
view
```

**Comment by BSharmi** [comment]
Thank you for the help! Tried the steps. Still cannot view widgets.
On inspect I see one of the many the errors which says 
```
Error: Script error for "nbextensions/nglview-js-widgets/extension"
```
I see the extension.js file is present under
```
~/anaconda3/envs/testing_nglview/share/jupyter/nbextensions/nglview-js-widgets
```
is anything else causing the error?

Thanks again!

**Comment by hainm** [comment]
can you please capture your screen with the inspection?

**Comment by BSharmi** [comment]
Attached. Sorry about the layout being rotated, I had to convert to pdf else the file upload failed

[erro_message.png.pdf](https://github.com/nglviewer/nglview/files/6073854/erro_message.png.pdf)

**Comment by hainm** [comment]
it's weird. The message says widgetsnbextension is not available. Can you try to import it and if it's not available, install it.

**Comment by BSharmi** [comment]
It is weird. I already checked it is available and can import

**Comment by BSharmi** [comment]
And the version is also matched with ipywidgets

**Comment by hainm** [comment]
Do you have any old distribution of `nglview` (the JS side):

This is from our FAQ:
https://github.com/nglviewer/nglview/blob/master/docs/FAQ.md#widget-not-shown
```
You are likely using older JavaScript distribution of nglview. Check if it is $HOME/.local/share/jupyter/nbextensions/nglview-js-widgets/, if Yes, delete it.

If you're using macos, might need to delete the folder $HOME/Library/Jupyter/nbextensions/nglview-js-widgets/
```

**Comment by hainm** [comment]
Additionally, what does `jupyter nbextension show` give you?

**Comment by BSharmi** [comment]
Thanks for the response!
I had seen the FAW, but have the nglview widgets under the anaconda env. I don't have any nbextensions folder under $HOME/.local/share/jupyter/

I see the following on running
```
jupyter nbextension  list
```
```
jupyter nbextension show
```
does not seem to recognize
```
Known nbextensions:
  config dir: /home/ubuntu/.jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
      nglview-js-widgets/extension  enabled 
      - Validating: OK
  config dir: /home/ubuntu/anaconda3/envs/default/etc/jupyter/nbconfig
    notebook section
      plotlywidget/extension  enabled 
      - Validating: OK
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
      nglview-js-widgets/extension  enabled 
      - Validating: OK
  config dir: /usr/local/etc/jupyter/nbconfig
    notebook section
      jupyter-js-widgets/extension  enabled 
      - Validating: OK
```

**Comment by hainm** [comment]
I run out of ideas now, I am sorry.

**Comment by BSharmi** [comment]
No problem thanks very much for helping!
