### ISSUE TITLE
QCElemental viewer reorients the molecule

### ISSUE THREAD

**Issue by robertodr** [nglviewer/nglview#953]
I am using the qcelemental viewer together with cube files. It seems that the molecule gets reoriented: the surface generated from the cube file is orthogonal to the molecular plane, which it shouldn't be. 

![Screenshot from 2021-03-02 12-19-23](https://user-images.githubusercontent.com/3708689/109641108-9e19f200-7b51-11eb-9ebc-578a29d04cac.png)

However, the constructor for the qcelemental molecule has `orient=False` by default.
I have tried visualizing the molecule with `show_text` and no reorientation happens. 

![Screenshot from 2021-03-02 12-19-37](https://user-images.githubusercontent.com/3708689/109641120-a3773c80-7b51-11eb-9721-5f24ff29986e.png)

Here a link to a demo binder: https://mybinder.org/v2/gh/ENCCS/nglview-demo/HEAD?filepath=nglview-demo.ipynb

- Version report

```bash
python -c 'import nglview; print(nglview.__version__)'
python -c 'import ipywidgets; print(ipywidgets.__version__)'
```
I am running version 2.7.7 of nglview and version 7.6.3 of ipywidgets.

**Comment by hainm** [comment]
hi @robertodr,

I guess it's because `nglview` is using `QCElementalObject.orient_molecule().to_string('nglview-sdf')
https://github.com/nglviewer/nglview/blob/00760a8f25c693ccbf90c67d0fc3e32ea27d0306/nglview/adaptor.py#L161

Please try to create another class without using the `orient_molecule`:

```
from nglview import Structure

class QCElementalStructure2(Structure):
    def __init__(self, obj):
        super().__init__()
        self._obj = obj
        self.ext = 'sdf'

    def get_structure_string(self):
        return self._obj.to_string('nglview-sdf')


import qcelemental as qcel

mol = qcel.models.Molecule.from_data(pyridine_xyz)

v0 = nv.NGLWidget(QCElementalStructure2(mol))

c1 = v0.add_component("HOMO.cube")
c1.clear()

c1.add_surface(isolevelType="value", isolevel=0.02, color="red")
c1.add_surface(isolevelType="value", isolevel=-0.02, color="blue")

v0
```

**Comment by robertodr** [comment]
Thank you! That does work. Any reason why the `orient_molecule` is needed?

**Comment by hainm** [comment]
I don't recall why. Thanks.
