### ISSUE TITLE
how to change color over time

### ISSUE THREAD

**Issue by mrjoness** [nglviewer/nglview#957]
I'm curious if there is a good way to change molecule color over the course of a trajectory. For example, I have four metastable states that are visited and it would be awesome if the configuration color reflected the state assignment at a given frame. 

Please let me know what you advise. Currently I see all the correct colors appear in the right order, however they just flash by very quickly and the final state color is saved for the actual video player:

widget = nglview.show_mdtraj(md_traj)
widget.add_ball_and_stick()

for i, x_ in enumerate(macro_traj):

    c = to_hex(cmap(x_))
    widget.update_ball_and_stick(color=c, frame=i)
    widget.remove_cartoon(component=i)

**Comment by hainm** [comment]
Hi, what’s “macro_traj”?

**Comment by mrjoness** [comment]
hi, this is an array containing the discrete state assignment for each frame in the md_traj trajectory   len(macro_traj)=len(md_traj.xyz). In this case there are four states so the possible values are [0, 1, 2, 3].

**Comment by hainm** [comment]
hi @mrjoness This is what I have in mind. You can use `time.sleep` to slow down the change.

<img width="1049" alt="Screen Shot 2021-03-09 at 11 14 05 PM" src="https://user-images.githubusercontent.com/4451957/110575647-37866c80-812d-11eb-9ce2-a545f813bd2d.png">

code:
```
#
from traitlets import observe
import nglview as nv
import pytraj as pt

traj = pt.datafiles.load_trpcage()[:4]
view = nv.show_pytraj(traj)
view

# 
import time

def on_frame_change(change):
    frame = change['new']
    colors = {0: 'red', 1: 'blue', 2: 'green'}
    if frame in colors:
        view.update_cartoon(color=colors[frame])
        time.sleep(0.1) # it's up to you
        

# 
view.observe(on_frame_change, names=['frame'])
```

**Comment by hainm** [comment]
Great.
