### ISSUE TITLE
MMTF trajectory

### ISSUE THREAD

**Issue by samarjeet** [nglviewer/nglview#958]
I am trying to find the most efficient file format for MD trajectory data for interactive viewing through the ngl. The ngl manuscript [[Rose et. al ](https://academic.oup.com/bioinformatics/article/34/21/3755/5021685)] mentioned that the MMTF format reduced the peak memory requirement. Is there a MMTF version for trajectory data as well? 

I posted a similar [inquiry](https://github.com/rcsb/mmtf-cpp/issues/42) on MMTF's issue page and was informed that MMTF format is only available for single structure data. I was wondering if the format has been extended by the NGL team to include trajectory data. It will be great to know if that has already been done so that I do not try to reinvent the wheel.

**Comment by hainm** [comment]
hi @samarjeet  You can use netcdf or dcd format.

Please see the trajectory player here: https://github.com/nglviewer/nglview/blob/master/README.md

**Comment by hainm** [comment]
By the way, this repo `nglview` is for using `NGL` via python in jupyter notebook.

**Comment by hainm** [comment]
I go ahead closing this issue. Feel free to reopen if needed.
