### ISSUE TITLE
Improve error message for nglview in JupyterLab

### ISSUE THREAD

**Issue by jennyfothergill** [nglviewer/nglview#959]
Hi there,
When running nglview in a jupyterlab instance when the lab-extension is not installed, the following error is displayed:

![Screen Shot 2021-03-11 at 1 14 22 PM](https://user-images.githubusercontent.com/39961845/110848823-bc77a000-826b-11eb-9a95-95d973d6f66c.png)

It seems others have found this error and the following inability to display the widget confusing (#944, #933), so perhaps an error message that gives the user the install instructions for the lab-extension would be helpful. :) A similar package, py3dmol, does this https://github.com/mosdef-hub/mbuild/issues/842#issuecomment-790914205_

- Version report
nglview 2.7.7
ipywidgets 7.6.3
```bash
python -c 'import nglview; print(nglview.__version__)'
python -c 'import ipywidgets; print(ipywidgets.__version__)'
```

**Comment by hainm** [comment]
hi @jennyfothergill: It's not up to `nglview` in this case. It's from `ipywidgets`. 

IMO, `py3dmol` does not use `ipywidgets` and it has its own way to handle the displaying.

**Comment by jennyfothergill** [comment]
Ah, OK. That's too bad. Thanks for the response, and I'll close this issue.

**Comment by hainm** [comment]
Thanks @jennyfothergill for your suggestion.
