### ISSUE TITLE
Simulation doesn't play on VScode Jupyter extension

### ISSUE THREAD

**Issue by phisanti** [nglviewer/nglview#961]
I have finished running an MD simulation with `openMM` and now I am trying to analyse the result with`mdtraj` and `nglview`. I just tried to do a quick visualisation loading the `.dcd` and the `.pdb` file. I notice I can see the system without problem, however, I cannot play the simulation (see attached image). If I put the files into pymol with a different computer, I can play the simulation without problem, so the files aren't the problem. Note that I am running nglview in the jupyter extension of VScode rather than a normal jupyter notebook (more details below).

Does anyone know how to solve this problem?

- Version report

```bash
nglview:   2.7.7
ipywidgets:   7.6.3
jupyter_client:   6.1.12    
jupyter_console:   6.3.0          
jupyter_core:   4.7.1            
jupyterlab_pygments:   0.1.2            
jupyterlab_widgets:   1.0.0        

Jupyter extension v2021.2.0
VScode extension 1.53.2

$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal      
```

![image](https://user-images.githubusercontent.com/33370667/112313510-d66ba680-8c9f-11eb-9292-c7bd5d42f4c5.png)

**Comment by hainm** [comment]
(I myself have zero knowledge about this).

**Comment by hainm** [comment]
It seems working for another user: https://leedavies.dev/index.php/2020/05/18/protein-visualization-in-vscode/

@phisanti Does your example work well in non-VSCode case (e.g: traditional notebook)?

**Comment by PicciF** [comment]
@phisanti i`m sorry but how did you make it display with nglview in vs code? to me print NGLWidget() and I don't know how to fix, can you help me pls?
