### ISSUE TITLE
jupyterlab: Do not require user to explicitly install nglview-js-widgets

### ISSUE THREAD

**Issue by hainm** [nglviewer/nglview#964]
IMO, ```pip install nglview```  or `conda install nglview` should be enough to work with jupyterlab. 
I am not talking about pulling `nglview-js-widgets` as dependency but about including it in `nglview` distribution.

**Comment by robertodr** [comment]
Yes, that should work. I will have a look at how to make it happen.

**Comment by hadim** [comment]
I think it's now recommended to use the jupyter packaging lib. See https://github.com/jupyterlab-contrib/jupyter-archive/blob/master/setup.py for an exemple.

**Comment by robertodr** [comment]
@hadim indeed that's in place already: https://github.com/nglviewer/nglview/blob/master/js/setup.py The problem to solve is how to package the contents of the `js` subfolder of the repo together with the existing `nglview` package.

**Comment by hadim** [comment]
I am pretty sure the package should only have one single setup.py file such as in https://github.com/jupyterlab-contrib/jupyter-archive/. This setup.py file generates a single pypi entry with everything in it (from what I know).

**Comment by hainm** [comment]
Thanks to @ericpre , we can make that happen for conda package.

https://github.com/ericpre/nglview-feedstock/blob/jlab3/recipe/build.sh

**Comment by ericpre** [comment]
Once there is a release on pypi, I am happy to make a pull request to the conda-forge feedstock. However, I guess the `setup.py` issue will still need to be sorted to work with `pip install nglview`?

**Comment by hainm** [comment]
> However, I guess the setup.py issue will still need to be sorted to work with pip install nglview

That's true. And we need to think about the dependencies too (e.g: not include `jupyterlab` as requirement).

**Comment by hainm** [comment]
@ericpre If `pip install nglview` is resolved, I don't think we need to make any change in `conda-forge` feedstock.

**Comment by ericpre** [comment]
> That's true. And we need to think about the dependencies too (e.g: not include jupyterlab as requirement).

Indeed, whether notebook or jupyterlab is installed should be left to the users to install at least one of the two and this is what is doing: https://github.com/ericpre/nglview-feedstock/blob/cbf8f8448a6047ade94a9380ba287795abf5e09e/recipe/meta.yaml#L28-L31, where only the minimum dependencies are required at runtime.


> @ericpre If `pip install nglview` is resolved, I don't think we need to make any change in `conda-forge` feedstock.

Only update the dependencies (add `jupyter-packaging` and others maybe), then.

**Comment by hainm** [comment]
> Only update the dependencies (add jupyter-packaging and others maybe), then.

yeah, `jupyterlab_widgets` is important one (not sure if this package will pull `jupyterlab` or not).

**Comment by hainm** [comment]
I have made a WIP PR here: https://github.com/nglviewer/nglview/pull/967

And you're all welcome to review. Please pay attention to the changes in `setup.py` and `package.json` files. 
Cheers

**Comment by hainm** [comment]
Resolved in #968  and #967. Published pip version too.

Basically, `pip install nglview` should work out of the box for both notebook and lab.
