### ISSUE TITLE
jupyterlab extension error: Error displaying widget: model not found

### ISSUE THREAD

**Issue by muh-hassani** [nglviewer/nglview#965]
I have nglview=2.7.7 alongside the labextension and jupyterlab=3.0.12 installed. I learned that the extension is [now compatible with Jlab3](https://github.com/nglviewer/nglview/issues/932), but I still get the following error when I want to use the extension:
```
Error displaying widget: model not found
```
As I read in [the merged PR](https://github.com/nglviewer/nglview/pull/955), it should be working. But surprisingly it is not working for me. Any idea, how to fix this?
By the way, when I list the lab extension, it reports that it is enabled and up-to-date.

**Comment by hainm** [comment]
What exactly did you do?

**Comment by muh-hassani** [comment]
Sorry for the incomplete description of the problem.
I have [a function](https://github.com/pyiron/pyiron_atomistics/blob/1a79a486009323cc2fbf8bfd380d081d44e5a6cb/pyiron_atomistics/atomistics/structure/_visualize.py#L207) which calls nglview. Below is the relevant snippet of the function:
```python3
import nglview
# Write the nglview protein-database-formatted string
struct = nglview.TextStructure(
    _ngl_write_structure(elements, positions, self._ref_atoms.cell)
)
# Parse the string into the displayable widget
view = nglview.NGLWidget(struct)
```  
**The situation is that this works well with jupyterlab=2.2.9, but it does not work with jupyterlab=3.0.12.**

**Comment by hainm** [comment]
> The situation is that this works well with jupyterlab=2.2.9, but it does not work with jupyterlab=3.0.12.

@muh-hassani  it does not work out of the box.

Please follow this: https://github.com/nglviewer/nglview/pull/955#issuecomment-811600734

(In short, you have to install the `pip` version of `nglview-js-widgets`)

**Comment by muh-hassani** [comment]
thanks @hainm. It worked using pip.
