### ISSUE TITLE
Viewing a subset of residues

### ISSUE THREAD

**Issue by iriziotis** [nglviewer/nglview#970]

**Comment by iriziotis** [comment]
Hello, I cannot view individual residues extracted from a PDB file (e.g. a catalytic site) in nglview 3.0.0. Tried everything, but no luck; all I see is a white screen, even when using the gui widget. Could you please help me with that? Attached is the pdb file I am trying to view (as .txt so that github can accept it). Note that whole molecules are shown without problems. The issue is only when trying to view individual residues or ligands.

[site.pdb](https://github.com/nglviewer/nglview/files/6288407/site.txt)

**Update: I realized that this happens when it tries to load more than 3 residues. Up to 3 residues are shown ok.

**Comment by hainm** [comment]
hi @iriziotis 

either:
- keep zooming out
- Or:
```
v.clear()
v.add_licorice()
v.center('HIS')
```

**Comment by iriziotis** [comment]
Oh, thanks, seems to work. Another thing, is there a way to view multiple PDBs in a single view? (Load multiple structure files, e.g. superimposed structures)

**Comment by hainm** [comment]
> Another thing, is there a way to view multiple PDBs in a single view? (Load multiple structure files, e.g. superimposed structures)

It depends on "how" you want to visualize it? As a trajectory where each structure belongs to a frame or multiple structures in a single frame (https://github.com/nglviewer/nglview/issues/765)

**Comment by iriziotis** [comment]
Switching between these two modes would be ideal. If I concatenate the PDB files, I can view the structures either as separate 'frames' or all of them simultaneously in one frame. The question is whether *multiple* PDB files can be loaded as frames, without having to concatenate them first. Thanks!!

**Comment by hainm** [comment]
>  Last thing: is there any way to change the automatic atom bonding distance threshold? Since I am viewing individual residues without 'CONECT' annotations, arbitrary bonds are generated automatically between atoms that should not be bonded.

I am not sure. Try to play with `NGL` to see if that helps: http://nglviewer.org/ngl/
Or may be write your own code to add `CONECT`.

**Comment by hainm** [comment]
Feel free to open other issues if needed. Cheers.
