### ISSUE TITLE
Displaying water [SOLVED]. Documentation link not working [NOT SOLVED].

### ISSUE THREAD

**Issue by cmartinotti** [nglviewer/nglview#972]
Hello, amazing work, i love this library. I'm trying to visualize the water molecules in a MDAnalysis universe, but it is never showing the waters. How do i make it display them? 

( I tried to look in the documentation, but the link is not working)

For anyone wondering i it works with the code

from nglview.datafiles import PDB, XTC
import nglview as nv
view = nv.show_mdanalysis(struct)
view.add_representation('licorice',selection="water")
view

I am leaving the post cause the documentation link is still not working

**Comment by hainm** [comment]
> I am leaving the post cause the documentation link is still not working

hi @cmartinotti: which link? thanks.

**Comment by cmartinotti** [comment]
> > I am leaving the post cause the documentation link is still not working
> 
> hi @cmartinotti: which link? thanks.
Reference link and Manual link on the documentation page :

http://arose.github.io/ngl/api/manual/index.html
http://arose.github.io/ngl/api/identifiers.html

**Comment by hainm** [comment]
Should be fixed now. Thanks

https://github.com/nglviewer/nglviewer.github.io/pull/2
