### ISSUE TITLE
nglview is not compatible with ipywidgets 7.5.1

### ISSUE THREAD

**Issue by wangfan860** [nglviewer/nglview#978]
Hello, I'm not able to import nglview in jupyter lab. I got an error "ImportError: cannot import name 'widget_image' from 'ipywidgets' (/opt/conda/lib/python3.8/site-packages/ipywidgets/__init__.py)". Please find the details in the screen capture below: 
![image](https://user-images.githubusercontent.com/18297731/118565846-86a5da80-b738-11eb-99e2-74f03622ffa9.png)

Any insight on it? thanks🙏 !!

**Comment by wangfan860** [comment]
Play around it a little bit more and now i can import nglview, but when I tried
```
import nglview as nv
demo_view = nv.demo()
demo_view
```
I got `Error displaying widget: model not found`

Then I tried `!pip install https://github.com/nglviewer/nglview/releases/download/v2.7.7/nglview-js-widgets-2.7.7.tar.gz # jupyter lab JS part`

and error was like 
```
ERROR: After October 2020 you may experience errors when installing or updating packages. This is because pip will change the way that it resolves dependency conflicts.

We recommend you use --use-feature=2020-resolver to test your packages with the new resolver before it becomes the default.

drsclient 0.1.4 requires jsonschema==2.5.1, but you'll have jsonschema 3.2.0 which is incompatible.
Successfully installed jsonschema-3.2.0 nglview-js-widgets-2.7.7
Error displaying widget: model not found
```

**Comment by hainm** [comment]
hi @wangfan860:

Please try `nglview` in a new conda environment first. Here is the commands: https://github.com/nglviewer/nglview/blob/master/devtools/nglview-jupyterlab.sh

Let me know if you are able to make that work.

**Comment by wangfan860** [comment]
Thanks so much ! @hainm However, it doesn't work, I still have `Error displaying widget: model not found` issue.

**Comment by hainm** [comment]
@wangfan860 oh, I think you're right that the latest `nglview` is not compatible with `ipywidgets 7.5.1`.

But if you used the bash script I posted above, your `ipywidgets` should be `7.6.3`

<img width="1266" alt="Screen Shot 2021-05-18 at 12 21 00 PM" src="https://user-images.githubusercontent.com/4451957/118688052-ae964c00-b7d3-11eb-94af-48db1808ca55.png">

**Comment by wangfan860** [comment]
Thanks so much for your prompt reply!!👍👍 @hainm  It's getting very close. Now it shows `Loading widget...` but still no actual figure. The `nglview-js-widgets` is successfully built according to the log.

![image](https://user-images.githubusercontent.com/18297731/118693967-2dd65080-b7d1-11eb-9913-57aa38605bda.png)

**Comment by hainm** [comment]
You must do something wrong. You don't need to build `nglview-js-widgets` because we don't need that package. 

Have you tried exactly what this script does? https://github.com/nglviewer/nglview/blob/master/devtools/nglview-jupyterlab.sh

**Comment by wangfan860** [comment]
@hainm Thank you for your help! Yep I tried the scripts. It seems the ipywidgets was DOWNGRADED from 7.6.3-pyhd3deb0d_0 --> 7.5.1-pyh9f0ad1d_1. The previous 7.6.3 was installed via pip.

```
!conda create -n lab python=3.8 -y 
!source activate lab
!conda install jupyterlab=3 nglview -c conda-forge -y
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.9.0
  latest version: 4.10.1

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /opt/conda/envs/lab

  added / updated specs:
    - python=3.8


The following NEW packages will be INSTALLED:

  _libgcc_mutex      conda-forge/linux-64::_libgcc_mutex-0.1-conda_forge
  _openmp_mutex      conda-forge/linux-64::_openmp_mutex-4.5-1_gnu
  ca-certificates    conda-forge/linux-64::ca-certificates-2020.12.5-ha878542_0
  certifi            conda-forge/linux-64::certifi-2020.12.5-py38h578d9bd_1
  ld_impl_linux-64   conda-forge/linux-64::ld_impl_linux-64-2.35.1-hea4e1c9_2
  libffi             conda-forge/linux-64::libffi-3.3-h58526e2_2
  libgcc-ng          conda-forge/linux-64::libgcc-ng-9.3.0-h2828fa1_19
  libgomp            conda-forge/linux-64::libgomp-9.3.0-h2828fa1_19
  libstdcxx-ng       conda-forge/linux-64::libstdcxx-ng-9.3.0-h6de172a_19
  ncurses            conda-forge/linux-64::ncurses-6.2-h58526e2_4
  openssl            conda-forge/linux-64::openssl-1.1.1k-h7f98852_0
  pip                conda-forge/noarch::pip-21.1.1-pyhd8ed1ab_0
  python             conda-forge/linux-64::python-3.8.10-h49503c6_1_cpython
  python_abi         conda-forge/linux-64::python_abi-3.8-1_cp38
  readline           conda-forge/linux-64::readline-8.1-h46c0cb4_0
  setuptools         conda-forge/linux-64::setuptools-49.6.0-py38h578d9bd_3
  sqlite             conda-forge/linux-64::sqlite-3.35.5-h74cdb3f_0
  tk                 conda-forge/linux-64::tk-8.6.10-h21135ba_1
  wheel              conda-forge/noarch::wheel-0.36.2-pyhd3deb0d_0
  xz                 conda-forge/linux-64::xz-5.2.5-h516909a_1
  zlib               conda-forge/linux-64::zlib-1.2.11-h516909a_1010


Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate lab
#
# To deactivate an active environment, use
#
#     $ conda deactivate

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.9.0
  latest version: 4.10.1

Please update conda by running

    $ conda update -n base conda



## Package Plan ##

  environment location: /opt/conda

  added / updated specs:
    - jupyterlab=3
    - nglview


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    ipywidgets-7.5.1           |     pyh9f0ad1d_1         101 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         101 KB

The following packages will be DOWNGRADED:

  ipywidgets                             7.6.3-pyhd3deb0d_0 --> 7.5.1-pyh9f0ad1d_1



Downloading and Extracting Packages
ipywidgets-7.5.1     | 101 KB    | ##################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
```

**Comment by hainm** [comment]
Don't do that in your notebook session.

Open a new bash terminal and try again.

And make sure the relaunch the lab notebook in your `lab` environment you've created.

**Comment by hainm** [comment]
>  The previous 7.6.3 was installed via pip.

If you created a new conda environment, called `lab` then there is NO ipywidgets installed yet.

**Comment by wangfan860** [comment]
Thanks!! I tried your way, however no luck still. The versions of ipywidgets and nv are exactly like yours, but I stuck at "Loading widget..." after the demo code.

**Comment by hainm** [comment]
Weird. Are you running it on mybinder? I see `/home/jovyan/` in your log.

**Comment by hainm** [comment]
In your notebook (assume you're using Chrome): Right Click -> Inpsect -> Console.
What do you see?

**Comment by hainm** [comment]
@wangfan860 Any further interest to debug or something else?
