### ISSUE TITLE
Save rather than download image function

### ISSUE THREAD

**Issue by psychemedia** [nglviewer/nglview#979]
The `.download_image(FILENAME)` method will *download* a snapshot of the current view to the browser download directory using a provided filename.

Is there a way to *save* the view as an image file into the current directory or location relative to the current directory? Or to an absolutely declared location?

**Comment by hainm** [comment]
@psychemedia Please see this: https://github.com/nglviewer/nglview/blob/master/docs/FAQ.md#how-to-make-nglview-view-object-write-png-file
