### ISSUE TITLE
Selection language for an MD analysis universe

### ISSUE THREAD

**Issue by Quynh2710** [nglviewer/nglview#981]
I have been trying to visualize an MDAnalysis trajectory of a protein with a ligand and a metal using nglview, but I have not been able to choose the representation for the ligand. I tried different combinations of selection, but I only able to get the ligand only when I use 'sele' : 'not (protein or water or ion or ligand)' , which does not make much sense and does not apply to other similar universes. Can you suggest what I should do to apply the representation only for the ligand?
![image](https://user-images.githubusercontent.com/71542306/119519208-3dace200-bd47-11eb-8da4-1359fb394bd1.png)

- Version report
![image](https://user-images.githubusercontent.com/71542306/119520527-5e296c00-bd48-11eb-8441-b0893c71192e.png)

**Comment by hainm** [comment]
Hi @Quynh2710: Is that possible to upload your file here?

**Comment by Quynh2710** [comment]
Yes, sure. This is the link to one of the MD Analysis universes that I use. The file is large, and I don't think of any other way to share it. 
https://drive.google.com/file/d/1AG0xBftTjjIqZ7Qhw94ppqDLrVfKHoNr/view?usp=sharing

**Comment by hainm** [comment]
It's too large (5G) for me. Why don't you just extract 1 frame and save it to pdb file and upload here?

**Comment by hainm** [comment]
And make sure to past exact commands so I can reproduce the issue (e.g: I am not sure how you created `view`).

**Comment by Quynh2710** [comment]
Thank you for helping me out and I'm sorry for the confusion. This is the file for one time step in the trajectory.
[universe.pdb.zip](https://github.com/nglviewer/nglview/files/6542672/universe.pdb.zip)
To view to the universe, this is the code that I used
![image](https://user-images.githubusercontent.com/71542306/119576535-ed557480-bd86-11eb-8b24-9c175aaa6bc4.png)
To selectively choose the representations for the ligand, this is the code that I used
![image](https://user-images.githubusercontent.com/71542306/119576663-30174c80-bd87-11eb-9116-12c832c7f457.png)

**Comment by hainm** [comment]
hi @Quynh2710, I think `nglview` (NGL under the hood) fails to recognize `TIP` as water. So it treats `TIP` molecules as ligands. I suggest to use `view.add_licorice('ANP')` explicitly for your ligand(s).

<img width="1153" alt="Screen Shot 2021-05-25 at 11 19 13 PM" src="https://user-images.githubusercontent.com/4451957/119597745-a3cd4f80-bdaf-11eb-9ca2-2e8d72a9d856.png">

**Comment by Quynh2710** [comment]
Thank you very much! It's worked beautifully now.

**Comment by hainm** [comment]
Cheers.
