### ISSUE TITLE
Trouble in downloading images

### ISSUE THREAD

**Issue by Amit-Harita** [nglviewer/nglview#982]
- I am trying to automate the snapshot rendering from a MD Traj using a function. But nglview not saving the images, it requires two different jupyter-notebook cells to download the image. Whereas in a single cell both view and view.download_image('example.png') not working.
- 

- Version report

python -c 'import nglview; print(nglview.__version__)'  ---- 2.7.7 
python -c 'import ipywidgets; print(ipywidgets.__version__)' ---- 7.6.3

"
#An example jupyter-notebook cell

import nglview as nv
view = nv.NGLWidget() 
filename = "test.gro"
view.add_component(filename)
view
view.download_image(filename='snap.png', factor=5, antialias=True, trim=False, transparent=False)
"
Whereas splitting the later part into two Jupiter-notebook cells works like
"#Cell1

import nglview as nv
view = nv.NGLWidget() 
filename = "test.gro"
view.add_component(filename)
view
"
"#Cell2
view.download_image(filename='snap.png', factor=5, antialias=True, trim=False, transparent=False)
"
Can you please comment/help? I need to make a function to automatically save the images every time on my call. Many thanks in advance

**Comment by hainm** [comment]
@Amit-Harita Please see this: https://github.com/nglviewer/nglview/blob/master/docs/FAQ.md#how-to-make-nglview-view-object-write-png-file
