### ISSUE TITLE
issue with gif videos

### ISSUE THREAD

**Issue by eguarnera** [nglviewer/nglview#986]
Hi, I'm having an issue with generating gif videos, I keep receiving the message that I need to install moviepy, imageio, etc. even though they are installed and the video is not generated.  The odd thing is that in another workstation with very similar settings I do not have this issue and the videos are successfully generated. Any suggestion?  

You have to install moviepy, imageio and ffmeg
pip install moviepy==0.2.2.11
pip install imageio==1.6

![image](https://user-images.githubusercontent.com/8078280/124113615-eb5c9080-da6b-11eb-8347-5ea48929d2ad.png)

- Version report

```bash
python -c 'import nglview; print(nglview.__version__)'
2.7.1
python -c 'import ipywidgets; print(ipywidgets.__version__)'
7.5.1
```

**Comment by hainm** [comment]
hi @eguarnera, 

what do you see in the notebook with below command? 
```
import moviepy.editor as mpy
```

(here is the source code: https://github.com/nglviewer/nglview/blob/4bab5accedc9131b6f58dbf11b887ee2b323416a/nglview/contrib/movie.py#L2-L7)

**Comment by eguarnera** [comment]
Hi @hainm,

Thanks for replying. This is what I get, the problem seems to be in importing tqdm, the weird thing is that tqdm is installed in the current env...

> `ImportError                               Traceback (most recent call last)
> <ipython-input-52-d20e93228310> in <module>
> ----> 1 import moviepy.editor as mpy
> 
> ~/anaconda3/envs/merck/lib/python3.7/site-packages/moviepy/editor.py in <module>
>      20 # Clips
>      21 
> ---> 22 from .video.io.VideoFileClip import VideoFileClip
>      23 from .video.io.ImageSequenceClip import ImageSequenceClip
>      24 from .video.io.downloader import download_webfile
> 
> ~/anaconda3/envs/merck/lib/python3.7/site-packages/moviepy/video/io/VideoFileClip.py in <module>
>       1 import os
>       2 
> ----> 3 from moviepy.video.VideoClip import VideoClip
>       4 from moviepy.audio.io.AudioFileClip import AudioFileClip
>       5 from moviepy.Clip import Clip
> 
> ~/anaconda3/envs/merck/lib/python3.7/site-packages/moviepy/video/VideoClip.py in <module>
>      12 from copy import copy
>      13 
> ---> 14 from tqdm import tqdm
>      15 import numpy as np
>      16 
> 
> ImportError: cannot import name 'tqdm' from 'tqdm' (unknown location)`

**Comment by hainm** [comment]
> from tqdm import tqdm

Yeah, I guess you need resolve this issue first.

**Comment by eguarnera** [comment]
Yeah, so I reinstalled tqdm, which seems to work and now I get these apparently innocuous messages by executing 

`import moviepy.editor as mpy
`

> In /home/merck/anaconda3/envs/merck/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
> The text.latex.preview rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
> In /home/merck/anaconda3/envs/merck/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
> The mathtext.fallback_to_cm rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
> In /home/merck/anaconda3/envs/merck/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: Support for setting the 'mathtext.fallback_to_cm' rcParam is deprecated since 3.3 and will be removed two minor releases later; use 'mathtext.fallback : 'cm' instead.
> In /home/merck/anaconda3/envs/merck/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
> The validate_bool_maybe_none function was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
> In /home/merck/anaconda3/envs/merck/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
> The savefig.jpeg_quality rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
> In /home/merck/anaconda3/envs/merck/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
> The keymap.all_axes rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
> In /home/merck/anaconda3/envs/merck/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
> The animation.avconv_path rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.
> In /home/merck/anaconda3/envs/merck/lib/python3.7/site-packages/matplotlib/mpl-data/stylelib/_classic_test.mplstyle: 
> The animation.avconv_args rcparam was deprecated in Matplotlib 3.3 and will be removed two minor releases later.

If I then try the code to generate the animation it seems to work

![image](https://user-images.githubusercontent.com/8078280/125045232-0e56f800-e09d-11eb-8580-6bad2a93dcd6.png)

However, all I get in the output file are just black snapshots. Any hint or further tests I could make?

**Comment by hainm** [comment]
hi @eguarnera, I am not sure how to debug. But just try to take 2 snapshots and use moviepy directly to see if you can see the video/gif?

https://stackoverflow.com/questions/44732602/convert-image-sequence-to-video-using-moviepy
