### ISSUE TITLE
NGLview widget not showing properly

### ISSUE THREAD

**Issue by Solin64** [nglviewer/nglview#989]
Hi there,

I am currently running through some tutorials on DeepChem and installed mdtraj and nglview locally using conda. When I executed the below code no 3D structures showed, unfortunately.

Currently running Python3.8.8 and nglview 3.0.3 installed.

Thank you for any advice or help you may provide

>>> if p and m:  # protein and molecule are readable by RDKit
...     print(pdbid, p.GetNumAtoms())
...     Chem.rdmolfiles.MolToPDBFile(p, '%s.pdb' % (pdbid))
...     Chem.rdmolfiles.MolToPDBFile(m, 'ligand_%s.pdb' % (pdbid))
...
6C0V 8914
>>> import mdtraj as md
>>> import nglview
>>> from IPython.display import display, Image
>>> protein_mdtraj=md.load_pdb('6C0V.pdb')
>>> ligand_mdtraj=md.load_pdb('ligand_6C0V.pdb')
>>> v=nglview.show_mdtraj(ligand_mdtraj)
>>> display(v)
NGLWidget()
>>> view=nglview.show_mdtraj(protein_mdtraj)
>>> display(view)
NGLWidget()

**Comment by hainm** [comment]
hi @Solin64: Did you use the notebook or just Ipython?

**Comment by Solin64** [comment]
> hi @Solin64: Did you use the notebook or just Ipython?

Hi hainm

Neither, I was using python locally through an anaconda terminal. Would it be better if I used Ipython?

Thank you!

**Comment by Solin64** [comment]
I've fixed it. Thank you very much!

I thought you could do it without using jupyterlabs or notebook, but I decided to just install jupyterlabs through conda and ran in on there, and it works! Still trying to get used to this system.

Regards

Thomas
