### ISSUE TITLE
How to get the unit cell vectors from different frames?

### ISSUE THREAD

**Issue by dprada** [nglviewer/nglview#992]
Hi! How can be the unit cell vectors from different frames be obtained?

For example, working with the demo trajectory, the coordinates from a given frame (3, for instance) can be obtained this way:

```
import mdtraj as md
import nglview as nv

traj = md.load(nv.datafiles.XTC, top=nv.datafiles.GRO)
view = nv.show_mdtraj(traj)
view.component_0.get_coordinates(3)
```

Is there a way to get the unit cell vectors for frame 3 from the nglview.NGLWidget object? The pbc box in 'nv.datafiles.XTC' is not constant in time.

Thanks in advance!

**Comment by dprada** [comment]
Sorry, moving this to Q&A

**Comment by hainm** [comment]
@dprada no worry, we're fine with either.
