### ISSUE TITLE
nglview on google colab

### ISSUE THREAD

**Issue by andresilvapimentel** [nglviewer/nglview#995]
It would be great if nglview could be run on google colab.

Is there a installation procedure for nglview on google colab?

**Comment by hainm** [comment]
hi @andresilvapimentel, it's up to google to implement the feature.

https://github.com/googlecolab/colabtools/issues/1049

**Comment by blois** [comment]
This should now be working:
https://colab.research.google.com/gist/blois/5ac0123ff66583f2578858fce7fdaf0b/nglview.ipynb

**Comment by hainm** [comment]
@blois thanks. But the trajectory player does not seem to work.

**Comment by blois** [comment]
Ah, good to know. Will dig into that.

**Comment by hainm** [comment]
> I believe that the trajectory player should now be working.

Thanks @blois. The molecule structure looks weird (duplicated) in codelab.

Saying I move the slider to value of 40.

In codelab: Try to slide the slider to see what I mean.
![image](https://user-images.githubusercontent.com/4451957/136494680-bedf72f5-7d0b-4cba-92fa-9cd117a1c38a.png)

In Jupyter notebook:
![image](https://user-images.githubusercontent.com/4451957/136494717-c5ad8ba4-12bd-491f-9d4b-396c934ff7c2.png)

**Comment by hainm** [comment]
> It would be great if nglview could be run on google colab.

Thanks to @blois, we can run `nglview` on google colab now. Cheers.

**Comment by davidlmobley** [comment]
I'm having problems with the trajectory viewer in Colab. I can confirm nglview now works, but the trajectory viewer is giving me jumbled molecules. Example to reproduce https://github.com/MobleyLab/drug-computing/issues/101

**Comment by elizabeththrall** [comment]
Hello all, I'm also having an issue with the ngl trajectory viewer in Colab.  The trajectory plays, but the first frame remains superimposed on all the subsequent frames.  The trajectory plays properly without the duplicated first frame in a Jupyter notebook outside of Colab.

I am using the MDAnalysis package to create a Universe object from an .xyz file and then show_mdanalysis to visualize it.  The notebook is attached in case it helps.  Thanks for supporting this great tool!

[notebookfile.zip](https://github.com/nglviewer/nglview/files/9056954/notebookfile.zip)

**Comment by hainm** [comment]
Hi,

It’s something colab should fix. I filed a case in colab repo and hopefully
google will fix it.

**Comment by hainm** [comment]
Here is the tracked case: https://github.com/googlecolab/colabtools/issues/2853#issuecomment-1171699299
