### ISSUE TITLE
Can it show dynamic bonds?

### ISSUE THREAD

**Issue by hellozhaoming** [nglviewer/nglview#996]
I'am doing an AIMD simulation. The molecule structures are very different from the initial ones.  The chemical bonds shown in nglview is very strange.
![image](https://user-images.githubusercontent.com/14068213/132944006-504af2f6-5d09-4e73-b8dc-4c6d196b10f6.png)

![image](https://user-images.githubusercontent.com/14068213/132944059-d66517b0-3905-4745-82b4-39f45e490cf5.png)

Can nglview define dynamic chemical bonds like VMD?

**Comment by hainm** [comment]
> Can nglview define dynamic chemical bonds like VMD?

Unfortunately `nglview` has not natively supported that.
