### ISSUE TITLE
Generate STL

### ISSUE THREAD

**Issue by ratleyg** [nglviewer/nglview#997]
Hi I am trying to generate an stl of a protein structure using nglview.

I generated the structure using the following code after downloading the pdb file:
```
parser = MMCIFParser()
structure = parser.get_structure('5iz2', 'C:\\5iz2.cif') //file path was modified here but works in notebook
```
I then run the stl writer code:
```
molsurf = new MolecularSurface(structure)
surf = molsurf.getSurface({type: 'av', probeRadius: 1.4})
stl = new StlWriter(surf)
stl.download('5iz2.stl')
```
And get the following error
```
    molsurf = new MolecularSurface(structure)
                  ^
SyntaxError: invalid syntax
```
removing the "new" 
```
molsurf = MolecularSurface(structure)
surf = molsurf.getSurface({type: 'av', probeRadius: 1.4})
stl = StlWriter(surf)
stl.download('5iz2.stl')
```
I get the error
```
NameError: name 'MolecularSurface' is not defined
```
Am I missing dependencies or maybe I am using the code completely wrong? Thanks for your help.

**Comment by hainm** [comment]
hi @ratleyg, it seems like you should ask `NGL` developers in here: https://github.com/nglviewer/ngl

This repo is `nglview`, which is more Python-related. Cheers.
