### ISSUE TITLE
Molecule above isosurface when setting negateIsolevel

### ISSUE THREAD

**Issue by wangenau** [nglviewer/nglview#998]
Hello,

I have some issues displaying orbitals from cube files with more than one phase.
When setting negateIsolevel to True, the molecule will always be rendered on top of the negative isosurface.
I have attached a screenshot and a simple script to show my problem at the bottom.
When trying the same with the [web application](https://nglviewer.org/ngl/) of ngl, everything will be displayed correctly.
Is this an issue with nglview or am I doing something wrong?

nglview version: 3.0.3

![orbitals](https://user-images.githubusercontent.com/15988797/134213206-da7f5515-99a3-466c-8521-9a9585413d5a.png)
* The green phase correctly colors the molecule, while the red does not

```python
from nglview import show_ase
from ase.io import read

file = 'orbital.cube'
atoms = read(file)
view = show_ase(atoms)

# Spin up
view.add_component(file)
view[1].clear()
view[1].add_surface(negateIsolevel=False,
                    color='lightgreen',
                    opacity=0.5,
                    side='front')

# Spin down
view.add_component(file)
view[2].clear()
view[2].add_surface(negateIsolevel=True,
                    color='red',
                    opacity=0.5,
                    side='front')
view
```

**Comment by hainm** [comment]
Thanks. I will try to reproduce and investigate this.

**Comment by hainm** [comment]
Time's flying and I still don't have time to try this. My apology.

**Comment by wangenau** [comment]
I can not reproduce this bug with the latest version anymore, therefor I will close this.
Another bug that I haven't mentioned here is that only one transparent isosurface will show the other one behind it.
I have fixed this for me by setting `depthWrite=False`.
