### ISSUE TITLE
Generating images in loop not working

### ISSUE THREAD

**Issue by scottwsides** [nglviewer/nglview#999]
I've seen the post about getting NGLView to export an image to a PNG file. The example show in NGLView works when changing representations in the same view that is being displayed in a separate cell. The code works for a single view as well. However if I put that code in a loop (I want to make lots of PNGs from different ngl view objects) then the separate view widgets never get displayed and the binary info that is in an object like   im0 = view.render_image() ; im0.value--> is empty. Is there *ANY* way of getting the rendered binary info created without generating the widget. I've tried a number of things to hack this... but unless the viewer is explicitly generated in a separate cell.... the binary image info is not generated. How to fix?

- Version report
```bash
python -c 'import nglview; print(nglview.__version__)' ---> 3.03
python -c 'import ipywidgets; print(ipywidgets.__version__)' ----> 7.6.3
```

**Comment by hainm** [comment]
> Is there ANY way of getting the rendered binary info created without generating the widget.

There is no way. You have to display the widget first.
But you can check this code of how to deal with multiple `render_image` calls. It might give you some ideas.
https://github.com/nglviewer/nglview/blob/master/docs/FAQ.md#how-to-make-nglview-view-object-write-png-file

**Comment by hainm** [comment]
You can use `from IPython.display import display` to programmatically display the view.

for view in [view0, view1]:
    display(view)

**Comment by scottwsides** [comment]
I of course saw the link you listed. HOwever, the Ipyhon display function
does help. However the displayed NGLview widget object interacts in a funny
way with the ipywidget 'Play' widget. I think I can make it work.
*Dr. Scott W Sides*
(303) 718-7028

**Comment by hainm** [comment]
Great.
